# Generated by Django 5.2.17 on 2026-09-26 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_googleidentity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoogleIdentity',
        ),
    ]
