"use client";

import { useEffect, useState } from "react";

const API_URL = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000";
type Budget = { id: number; year: number; total_income: string; total_expenses: string; notes: string };
type Report = { id: number; title: string; period_start: string; period_end: string; total_tithes: string; total_offerings: string; total_expenses: string; notes: string };

const money = (value: string) => `KES ${Number(value).toLocaleString("en-KE", { minimumFractionDigits: 2 })}`;

export default function FinancialPage() {
  const [budgets, setBudgets] = useState<Budget[]>([]);
  const [reports, setReports] = useState<Report[]>([]);
  const [loaded, setLoaded] = useState(false);
  useEffect(() => { Promise.all([fetch(`${API_URL}/api/members/budgets/`).then((response) => response.ok ? response.json() : []), fetch(`${API_URL}/api/members/reports/`).then((response) => response.ok ? response.json() : [])]).then(([budgetData, reportData]) => { setBudgets(budgetData); setReports(reportData); }).finally(() => setLoaded(true)); }, []);
  return <main className="min-h-screen bg-[#f7f4ee] px-6 py-10 text-[#26352f] sm:py-16"><div className="mx-auto max-w-5xl"><div className="max-w-3xl"><h1 className="mt-3 text-4xl font-semibold tracking-tight sm:text-6xl">Stewardship and accountability</h1></div><section id="budget" className="scroll-mt-28 pt-12"><h2 className="text-2xl font-semibold">Church budget</h2><div className="mt-5 grid gap-5 md:grid-cols-2">{budgets.map((budget) => <article key={budget.id} className="rounded-xl border border-[#dfdbd1] bg-white p-6"><p className="text-sm font-semibold text-[#b36b3c]">{budget.year} budget</p><div className="mt-5 grid grid-cols-2 gap-4"><div><p className="text-xs uppercase tracking-wider text-[#617068]">Income</p><p className="mt-1 text-lg font-semibold">{money(budget.total_income)}</p></div><div><p className="text-xs uppercase tracking-wider text-[#617068]">Expenses</p><p className="mt-1 text-lg font-semibold">{money(budget.total_expenses)}</p></div></div>{budget.notes && <p className="mt-5 text-sm leading-6 text-[#617068]">{budget.notes}</p>}</article>)}</div>{loaded && budgets.length === 0 && <p className="mt-5 text-sm text-[#617068]">No public budget has been published yet.</p>}</section><section id="reports" className="scroll-mt-28 border-t border-[#dfdbd1] pt-12"><h2 className="text-2xl font-semibold">Financial reports</h2><div className="mt-5 divide-y divide-[#dfdbd1] rounded-xl border border-[#dfdbd1] bg-white">{reports.map((report) => <article key={report.id} className="p-6"><div className="flex flex-wrap justify-between gap-4"><h3 className="text-lg font-semibold">{report.title}</h3><p className="text-sm text-[#617068]">{report.period_start} – {report.period_end}</p></div><div className="mt-5 grid gap-4 text-sm sm:grid-cols-3"><p><span className="block text-xs uppercase tracking-wider text-[#617068]">Tithes</span><span className="font-semibold">{money(report.total_tithes)}</span></p><p><span className="block text-xs uppercase tracking-wider text-[#617068]">Offerings</span><span className="font-semibold">{money(report.total_offerings)}</span></p><p><span className="block text-xs uppercase tracking-wider text-[#617068]">Expenses</span><span className="font-semibold">{money(report.total_expenses)}</span></p></div>{report.notes && <p className="mt-4 text-sm leading-6 text-[#617068]">{report.notes}</p>}</article>)}</div>{loaded && reports.length === 0 && <p className="mt-5 text-sm text-[#617068]">No public financial reports have been published yet.</p>}</section></div></main>;
}
