"use client";

import { FormEvent, useState } from "react";

const API_URL = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000";

export default function TestimoniesPage() {
  const [anonymous, setAnonymous] = useState(false); const [testimony, setTestimony] = useState(""); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [message, setMessage] = useState("");
  function resizeTextarea(element: HTMLTextAreaElement) { element.style.height = "auto"; element.style.height = `${element.scrollHeight}px`; }
  async function submitTestimony(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setMessage(""); const response = await fetch(`${API_URL}/api/members/prayer-requests/`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ request_text: `Testimony: ${testimony}`, name: anonymous ? "" : name, email: anonymous ? "" : email, anonymous }) }); setMessage(response.ok ? "Thank you for sharing your testimony." : "We could not submit your testimony. Please try again."); if (response.ok) setTestimony(""); }
  return <main className="min-h-screen bg-[#f7f4ee] px-6 py-6 text-[#26352f] sm:py-8"><div className="mx-auto max-w-3xl"><h1 className="text-4xl font-semibold tracking-tight sm:text-6xl">Testimonies</h1><p className="mt-3 text-lg leading-8 text-[#617068]">Share how God has been working in your life and encourage someone else.</p><form onSubmit={submitTestimony} className="mt-6 rounded-3xl bg-white p-5 shadow-sm ring-1 ring-[#dfdbd1] sm:p-7"><label className="block text-sm font-medium">Your testimony<textarea required rows={3} value={testimony} onChange={(event) => { setTestimony(event.target.value); resizeTextarea(event.currentTarget); }} className="mt-2 block min-h-24 w-full resize-none overflow-hidden rounded-xl border border-[#c9c5bb] px-4 py-3" placeholder="Tell us what you would like to share..." /></label><label className="mt-3 flex items-center gap-3 text-sm"><input type="checkbox" checked={anonymous} onChange={(event) => setAnonymous(event.target.checked)} />Submit anonymously</label>{!anonymous && <div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="block text-sm font-medium">Name<input required value={name} onChange={(event) => setName(event.target.value)} className="mt-2 w-full rounded-xl border border-[#c9c5bb] px-4 py-3" /></label><label className="block text-sm font-medium">Email<input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} className="mt-2 w-full rounded-xl border border-[#c9c5bb] px-4 py-3" /></label></div>}<button className="mt-5 w-full rounded-full bg-[#b36b3c] px-6 py-3 font-semibold text-white">Submit testimony</button>{message && <p className="mt-4 rounded-xl bg-[#eef2ed] p-4 text-sm">{message}</p>}</form></div></main>;
}
