"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";

const API_URL = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000";

export default function LoginPage() {
  const [username, setUsername] = useState(""); const [password, setPassword] = useState(""); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false);
  async function handleSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setMessage(""); try { const response = await fetch(`${API_URL}/api/auth/token/`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ username, password }) }); const data = await response.json(); if (!response.ok) throw new Error(Object.values(data).flat().join(" ") || "Unable to sign in."); localStorage.setItem("access_token", data.access); setMessage("You are signed in."); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to connect to the server."); } finally { setLoading(false); } }
  return <main className="flex min-h-[calc(100vh-73px)] items-start justify-center bg-[#f7f4ee] px-6 pt-6 text-[#26352f] sm:items-center sm:py-8"><section className="w-full max-w-md rounded-3xl bg-white p-6 shadow-sm ring-1 ring-[#dfdbd1] sm:p-8"><h1 className="text-2xl font-semibold tracking-tight sm:text-3xl">Welcome back</h1><p className="mt-2 text-sm text-[#617068]">Sign in to your church member account.</p><form className="mt-6 space-y-4" onSubmit={handleSubmit}><label className="block text-sm font-medium">Username<input className="mt-1.5 w-full rounded-xl border border-[#c9c5bb] px-4 py-2.5 outline-none focus:border-[#b36b3c]" value={username} onChange={(event) => setUsername(event.target.value)} required /></label><label className="block text-sm font-medium">Password<input type="password" className="mt-1.5 w-full rounded-xl border border-[#c9c5bb] px-4 py-2.5 outline-none focus:border-[#b36b3c]" value={password} onChange={(event) => setPassword(event.target.value)} required /></label><button disabled={loading} className="w-full rounded-full bg-[#26352f] px-5 py-3 font-medium text-white disabled:opacity-60">{loading ? "Please wait..." : "Sign in"}</button><div className="text-center pt-1"><Link href="/forgot-password" className="text-xs font-semibold text-[#b36b3c] hover:underline sm:text-sm">Forgot password?</Link></div></form>{message && <p className="mt-4 rounded-xl bg-[#f7f4ee] p-3 text-xs text-[#617068] sm:text-sm">{message}</p>}<p className="mt-6 border-t border-[#dfdbd1] pt-5 text-center text-xs text-[#617068] sm:text-sm">Need a member account? <Link href="/enroll" className="font-semibold text-[#b36b3c] hover:underline">Request member enrollment</Link></p></section></main>;
}
