"use client";

import { FormEvent, useState } from "react";

const API_URL = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000";

export default function LoginPage() {
  const [username, setUsername] = useState(""); const [password, setPassword] = useState(""); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false);
  async function handleSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setMessage(""); try { const response = await fetch(`${API_URL}/api/auth/token/`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ username, password }) }); const data = await response.json(); if (!response.ok) throw new Error(Object.values(data).flat().join(" ") || "Unable to sign in."); localStorage.setItem("access_token", data.access); setMessage("You are signed in."); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to connect to the server."); } finally { setLoading(false); } }
return <main className="flex min-h-screen items-start justify-center bg-[#f7f4ee] px-6 pt-20 sm:pt-24 text-[#26352f]"><section className="w-full max-w-md rounded-3xl bg-white p-8 shadow-sm ring-1 ring-[#dfdbd1] sm:p-10"><h1 className="text-3xl font-semibold tracking-tight">Welcome back</h1><p className="mt-3 text-[#617068]">Sign in to your church official account.</p><form className="mt-10 space-y-6" onSubmit={handleSubmit}><label className="block text-sm font-medium">Username<input className="mt-2 w-full rounded-xl border border-[#c9c5bb] px-4 py-3 outline-none focus:border-[#b36b3c]" value={username} onChange={(event) => setUsername(event.target.value)} required /></label><label className="block text-sm font-medium">Password<input type="password" className="mt-2 w-full rounded-xl border border-[#c9c5bb] px-4 py-3 outline-none focus:border-[#b36b3c]" value={password} onChange={(event) => setPassword(event.target.value)} required /></label><button disabled={loading} className="w-full rounded-full bg-[#26352f] px-5 py-3.5 font-medium text-white disabled:opacity-60">{loading ? "Please wait..." : "Sign in"}</button></form>{message && <p className="mt-5 rounded-xl bg-[#f7f4ee] p-4 text-sm text-[#617068]">{message}</p>}</section></main>;
}
