
const categories = [
  { name: "God", beliefs: [["Holy Scriptures", "The Bible is God's written Word and the trusted foundation for faith and life."], ["The Trinity", "There is one God-Father, Son, and Holy Spirit-united in eternal love and purpose."], ["God the Father", "The Father is the loving Creator, Sustainer, and source of all that is good."], ["God the Son", "Jesus Christ is fully God and fully human, our Creator, Saviour, and Lord."], ["God the Holy Spirit", "The Holy Spirit reveals Christ, transforms lives, and equips God's people for service."]] },
  { name: "Humanity", beliefs: [["Creation", "God created the world and humanity, and creation reflects His wisdom and goodness."], ["Nature of Humanity", "Human beings were created in God's image, but sin has affected every part of human life and brought death."]] },
  { name: "Salvation", beliefs: [["The Great Controversy", "A conflict between Christ and Satan explains the origin of sin and God's work to restore His creation."], ["The Life, Death, and Resurrection of Christ", "Through Jesus' life, sacrifice, and resurrection, God provides reconciliation and victory over sin."], ["The Experience of Salvation", "By grace through faith, believers receive forgiveness, a new life in Christ, and the assurance of God's love."], ["Growing in Christ", "Christian growth involves prayer, Bible study, worship, fellowship, service, and daily dependence on Christ."]] },
  { name: "The Church", beliefs: [["The Church", "The church is the community of believers who confess Jesus Christ and are called to share His gospel."], ["The Remnant and Its Mission", "God calls a faithful people to proclaim the everlasting gospel and prepare the world for Christ's return."], ["Unity in the Body of Christ", "In Christ, believers from every nation and background are united as one family."], ["Baptism", "Baptism by immersion expresses faith in Christ, repentance, and entry into the fellowship of His body."], ["The Lord's Supper", "Communion remembers Christ's sacrifice and celebrates humility, reconciliation, and fellowship among believers."]] },
  { name: "Daily Christian Life", beliefs: [["Spiritual Gifts and Ministries", "The Holy Spirit gives every believer gifts to serve the church and advance God's mission."], ["The Gift of Prophecy", "The prophetic gift is one way God guides His people and strengthens the church's witness."], ["The Law of God", "God's law expresses His character and shows the principles of love, justice, and faithful living."], ["The Sabbath", "The seventh-day Sabbath is a weekly gift of rest, worship, fellowship, and remembrance of the Creator."], ["Stewardship", "Everything belongs to God; believers manage their time, abilities, resources, and care for creation in partnership with Him."], ["Christian Behavior", "Christians are called to live with integrity, purity, compassion, self-control, and respect for the dignity of others."], ["Marriage and the Family", "Marriage and family are gifts from God, designed for loving commitment, nurture, and mutual support."]] },
  { name: "Restoration", beliefs: [["Christ's Ministry in the Heavenly Sanctuary", "Christ ministers for believers as our High Priest, applying the benefits of His sacrifice and preparing the way for final restoration."], ["The Second Coming of Christ", "Jesus will return personally, visibly, and gloriously to gather His people and bring an end to sin."], ["Death and Resurrection", "Death is an unconscious state until the resurrection, when Christ calls the dead to life."], ["The Millennium and the End of Sin", "After Christ's return, God will bring judgment to its conclusion and permanently end sin, suffering, and death."], ["The New Earth", "God will create a renewed earth where His people live forever in joy, peace, worship, and fellowship with Him."]] },
];

export default function BeliefsPage() {
  return <main className="min-h-screen bg-[#f7f4ee] text-[#26352f]"><div className="mx-auto max-w-6xl px-6 py-12 lg:px-8 lg:py-16"><div className="max-w-3xl"><h1 className="mt-3 text-4xl font-semibold tracking-tight sm:text-6xl">The 28 fundamental beliefs</h1><p className="mt-5 text-lg leading-8 text-[#617068]">These beliefs summarize how Seventh-day Adventists understand the teaching of Scripture. They point us to Jesus and shape the way we worship, serve, and live.</p></div><div className="mt-12 space-y-12">{categories.map((category) => <section key={category.name}><h2 className="border-b border-[#c9d5ca] pb-3 text-2xl font-semibold">{category.name}</h2><div className="mt-6 grid gap-4 md:grid-cols-2">{category.beliefs.map(([title, description], index) => <article key={title} className="rounded-xl border border-[#dfdbd1] bg-white p-6"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-[#b36b3c]">{categories.slice(0, categories.indexOf(category)).reduce((count, item) => count + item.beliefs.length, 0) + index + 1}</p><h3 className="mt-2 text-lg font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-[#617068]">{description}</p></article>)}</div></section>)}</div><p className="mt-14 border-t border-[#dfdbd1] pt-6 text-sm leading-6 text-[#617068]">Read the official explanation of the <a href="https://www.adventist.org/beliefs/" target="_blank" rel="noreferrer" className="font-semibold text-[#b36b3c] hover:underline">28 Fundamental Beliefs on Adventist.org &rarr;</a></p></div></main>;
}
