# Generated by Django 5.2.15 on 2026-08-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_contribution_donor_email_contribution_donor_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchFinancialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_tithes', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_offerings', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('published_to_members', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='PrayerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_text', models.TextField()),
                ('name', models.CharField(blank=True, max_length=160)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('anonymous', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('prayed', 'Prayed'), ('closed', 'Closed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='contribution',
            name='giving_type',
            field=models.CharField(choices=[('financial', 'Financial'), ('in_kind', 'In-kind')], default='financial', max_length=20),
        ),
        migrations.AddField(
            model_name='contribution',
            name='item_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
