# Generated by Django 5.2.15 on 2026-08-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_churchfinancialreport_prayerrequest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SabbathEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('name', models.CharField(default='Sabbath Worship', max_length=160)),
                ('program_text', models.TextField(blank=True)),
                ('program_file', models.FileField(blank=True, null=True, upload_to='sabbath-programs/')),
                ('published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
