# Generated by Django 5.2.16 on 2026-08-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_sabbathevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='sabbathevent',
            name='department',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
