# Generated by Django 5.2.15 on 2026-08-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_sabbathevent_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='sabbathevent',
            name='leader',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
