# Generated by Django 5.2.15 on 2026-08-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_sabbathevent_leader'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church_name', models.CharField(default='Loma Linda SDA Church, Meru', max_length=160)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('midweek_vespers_link', models.URLField(blank=True)),
                ('midweek_vespers_time', models.CharField(default='Wednesday · 8:00 PM – 9:00 PM', max_length=120)),
                ('friday_vespers_time', models.CharField(default='Friday · 5:30 PM – 6:30 PM', max_length=120)),
                ('sabbath_time', models.CharField(default='Saturday · 8:00 AM – 4:00 PM', max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
