# Generated by Django 5.2.15 on 2026-08-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_churchsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('published_to_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('leader', 'Church leader'), ('admin', 'Administrator'), ('finance', 'Finance team'), ('choir_director', 'Choir director'), ('children_ministry', 'Children ministry'), ('men_ministry', 'Adventist men ministries'), ('women_ministry', 'Adventist Women Ministries'), ('chaplaincy', 'Chaplaincy')], default='member', max_length=30),
        ),
    ]
