# Generated by Django 5.2.16 on 2026-08-05 14:43

from django.db import migrations, models


def seed_giving_purposes(apps, schema_editor):
    GivingPurpose = apps.get_model('members', 'GivingPurpose')
    GivingPurpose.objects.bulk_create([
        GivingPurpose(name=name)
        for name in ('General giving', 'Tithe', 'Church development', 'Local Church Budget (LCB)', 'Msamaria Mwema', 'Missions')
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_create_church_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='GivingPurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(seed_giving_purposes, migrations.RunPython.noop),
    ]
