# Generated by Django 5.2.16 on 2026-08-05 15:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_givingpurpose'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('leader', 'Church leader'), ('admin', 'Administrator'), ('finance', 'Finance team'), ('treasurer', 'Treasurer'), ('choir_director', 'Choir director'), ('children_ministry', 'Children ministry'), ('men_ministry', 'Adventist men ministries'), ('women_ministry', 'Adventist Women Ministries'), ('chaplaincy', 'Chaplaincy')], default='member', max_length=30),
        ),
    ]
