# Generated by Django 5.2.15 on 2026-08-06 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='expires_at',
            field=models.DateField(blank=True, help_text='Date up to which the announcement will be displayed', null=True),
        ),
    ]
