# Generated by Django 5.2.15 on 2026-08-06 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_testimony'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childdedicationrequest',
            name='email',
        ),
        migrations.RemoveField(
            model_name='childdedicationrequest',
            name='parent_name',
        ),
        migrations.RemoveField(
            model_name='childdedicationrequest',
            name='requested_date',
        ),
        migrations.AddField(
            model_name='childdedicationrequest',
            name='father_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='childdedicationrequest',
            name='mother_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='childdedicationrequest',
            name='child_dob',
            field=models.DateField(default='2026-01-01'),
            preserve_default=False,
        ),
    ]
