# Generated by Django 5.2.15 on 2026-08-06 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_remove_childdedicationrequest_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('meeting_date', models.DateField()),
                ('agenda', models.TextField(help_text='Meeting agenda items')),
                ('minutes', models.TextField(blank=True, help_text='Recorded board meeting minutes')),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('completed', 'Completed'), ('archived', 'Archived')], default='upcoming', max_length=20)),
                ('reference_file', models.FileField(blank=True, null=True, upload_to='board-materials/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-meeting_date'],
            },
        ),
        migrations.CreateModel(
            name='ChurchCorrespondence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('sender_or_recipient', models.CharField(max_length=160)),
                ('category', models.CharField(choices=[('clerk_letter', 'Clerk Letter'), ('recommendation', 'Letter of Recommendation'), ('board_notice', 'Board Notice'), ('general', 'General Correspondence')], default='general', max_length=30)),
                ('body', models.TextField()),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MembershipTransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=160)),
                ('transfer_type', models.CharField(choices=[('incoming', 'Incoming Transfer'), ('outgoing', 'Outgoing Transfer')], default='incoming', max_length=20)),
                ('other_church', models.CharField(help_text='Previous or destination church name', max_length=160)),
                ('phone_number', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under review'), ('approved', 'Approved'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('clerk_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('clerk', 'Church Clerk'), ('elder', 'Elder / First Elder'), ('youth_leader', 'Youth Ministries Leader'), ('choir_director', 'Choir Director'), ('children_ministry', 'Children Ministry'), ('men_ministry', 'Adventist Men Ministries'), ('women_ministry', 'Adventist Women Ministries'), ('chaplaincy', 'Chaplaincy'), ('finance', 'Finance Team'), ('treasurer', 'Treasurer'), ('leader', 'Church Leader'), ('admin', 'Administrator')], default='member', max_length=30),
        ),
        migrations.CreateModel(
            name='ChurchNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
