# Generated by Django 5.2.15 on 2026-08-06 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_boardmeeting_churchcorrespondence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchfinancialreport',
            name='period_type',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], default='monthly', max_length=20),
        ),
    ]
