# Generated by Django 5.2.15 on 2026-08-06 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_churchfinancialreport_period_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_name', models.CharField(max_length=160)),
                ('phone_number', models.CharField(max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('visitation_type', models.CharField(choices=[('pastoral', 'Pastoral Care & Prayer'), ('sick', 'Sick / Hospital Visitation'), ('bereavement', 'Bereavement / Grief Support'), ('family', 'Home Blessing / Family Visit'), ('other', 'Other')], default='pastoral', max_length=40)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('preferred_time', models.CharField(blank=True, max_length=80)),
                ('location_description', models.TextField(help_text='Landmarks or house address description')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
