# Generated by Django 5.2.16 on 2026-08-08 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0026_privacy_acceptance'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='receipt_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
