# Generated by Django 5.2.15 on 2026-08-08 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0028_friend_pendingtestimony_testimony_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='account_type',
            field=models.CharField(choices=[('member', 'Member'), ('friend', 'Friend of Loma Linda')], default='member', max_length=20),
        ),
        migrations.AlterField(
            model_name='enrollmentrequest',
            name='joining_mode',
            field=models.CharField(choices=[('baptism', 'Baptism'), ('membership_transfer', 'Membership transfer'), ('friend', 'Friend of Loma Linda')], default='baptism', max_length=30),
        ),
        migrations.AlterField(
            model_name='enrollmentrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
    ]
