# Generated by Django 5.2.15 on 2026-08-08 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0029_memberprofile_account_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentrequest',
            name='current_church',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='testimony',
            name='requested_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testimony',
            name='requested_time',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
