# Generated by Django 5.2.15 on 2026-08-08 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0030_enrollmentrequest_current_church_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiptransferrequest',
            name='reason',
            field=models.TextField(blank=True, help_text='Reason for the transfer'),
        ),
    ]
