# Generated by Django 5.2.15 on 2026-08-08 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0032_enrollmentrequest_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchsettings',
            name='live_service_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='churchsettings',
            name='live_service_link',
            field=models.URLField(blank=True),
        ),
    ]
