# Generated by Django 5.2.15 on 2026-08-08 06:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0035_fundraisingcampaign_contribution_campaign'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fundraisingcampaign',
            name='target_groups',
            field=models.JSONField(blank=True, default=list, help_text='List of assigned group/department keys'),
        ),
        migrations.CreateModel(
            name='CampaignCardAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(default='General Member', max_length=60)),
                ('referral_token', models.CharField(default=uuid.uuid4, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_assignments', to='members.fundraisingcampaign')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('campaign', 'member')},
            },
        ),
        migrations.AddField(
            model_name='contribution',
            name='card_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to='members.campaigncardassignment'),
        ),
    ]
