# Generated by Django 5.2.15 on 2026-08-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0036_fundraisingcampaign_target_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportsubmission',
            name='submission_type',
            field=models.CharField(choices=[('idea', 'Idea'), ('moral_support', 'Prayer and moral support'), ('partnership', 'Partnership request')], max_length=20),
        ),
    ]
