# Generated by Django 5.2.15 on 2026-08-25 19:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0039_seed_ministry_giving_purposes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_on', models.DateField(default=django.utils.timezone.localdate)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purpose', models.CharField(default='General giving', max_length=120)),
                ('donor_name', models.CharField(blank=True, max_length=160)),
                ('receipt_number', models.CharField(blank=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_contributions_entered', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContributionReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reconciliation_date', models.DateField(unique=True)),
                ('digital_amount_confirmed', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cash_amount_counted', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('reconciled_at', models.DateTimeField(auto_now=True)),
                ('reconciled_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contribution_reconciliations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reconciliation_date'],
            },
        ),
    ]
