# Generated by Django 5.2.15 on 2026-09-04 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0040_cashcontribution_contributionreconciliation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='action_prompt',
            field=models.CharField(blank=True, help_text='Optional prompt for pledge or response', max_length=255),
        ),
        migrations.AddField(
            model_name='announcement',
            name='action_type',
            field=models.CharField(choices=[('acknowledge', 'Acknowledge'), ('pledge', 'Pledge'), ('respond', 'Respond')], default='acknowledge', max_length=20),
        ),
        migrations.AddField(
            model_name='announcement',
            name='is_popup',
            field=models.BooleanField(default=True, help_text='Pop up automatically to users requiring action'),
        ),
        migrations.CreateModel(
            name='AnnouncementResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('acknowledge', 'Acknowledge'), ('pledge', 'Pledge'), ('respond', 'Respond')], max_length=20)),
                ('pledge_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('response_text', models.TextField(blank=True)),
                ('respondent_name', models.CharField(blank=True, max_length=120)),
                ('respondent_phone', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='members.announcement')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcement_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
