# Generated by Django 5.2.17 on 2026-09-12 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0042_seed_vesper_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchsettings',
            name='clarion_call_heading',
            field=models.TextField(default='A place to belong.\nA faith to share.\nA hope that transforms lives.'),
        ),
        migrations.AddField(
            model_name='churchsettings',
            name='clarion_call_subtext',
            field=models.TextField(default="Join Loma Linda SDA Church, Meru as we study God's Word, support one another, and reach out to our community with faith and compassion."),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('airtel', 'Airtel Money'), ('card', 'Card')], default='mpesa', max_length=20),
        ),
    ]
