# Generated by Django 5.2.17 on 2026-09-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0043_churchsettings_clarion_call_heading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='education_level',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='employment_status',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='marital_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='profession',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='residence',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
