# Generated by Django 5.2.17 on 2026-09-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0044_memberprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchsettings',
            name='church_name',
            field=models.CharField(default='Loma Linda SDA Church, Meru', max_length=160),
        ),
        migrations.AlterField(
            model_name='churchsettings',
            name='clarion_call_subtext',
            field=models.TextField(default="Join Loma Linda SDA Church, Meru as we study God's Word, support one another, and reach out to our community with faith and compassion."),
        ),
        migrations.AlterField(
            model_name='enrollmentrequest',
            name='joining_mode',
            field=models.CharField(choices=[('baptism', 'Baptism'), ('membership_transfer', 'Membership transfer'), ('friend', 'Friend of Loma Linda SDA')], default='baptism', max_length=30),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='account_type',
            field=models.CharField(choices=[('member', 'Member'), ('friend', 'Friend of Loma Linda SDA')], default='member', max_length=20),
        ),
    ]
