# Generated by Django 5.2.17 on 2026-09-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0046_fundraisingcampaign_fields_and_seed_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='sharing_option',
            field=models.CharField(blank=True, choices=[('site', 'On the Site'), ('sms', 'Through SMS'), ('email', 'Through Email'), ('all', 'All')], default='site', max_length=20),
        ),
    ]
