# Generated by Django 5.2.17 on 2026-09-17 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0047_announcement_sharing_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='givingpurpose',
            name='account_name',
            field=models.CharField(blank=True, help_text='M-Pesa / Giving account reference name (e.g. tithe, offering)', max_length=60),
        ),
    ]
