# Generated by Django 5.2.17 on 2026-09-17 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0048_givingpurpose_account_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='gifts',
            field=models.TextField(blank=True, default='', help_text='Spiritual gifts and talents of the member'),
        ),
    ]
