# Generated by Django 5.2.17 on 2026-09-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0049_memberprofile_gifts'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='whatsapp_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='disability',
            field=models.TextField(blank=True, default='', help_text='Disability or special needs of the member'),
        ),
    ]
