# Generated by Django 5.2.17 on 2026-09-17 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0050_memberprofile_disability_and_whatsapp_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberprofile',
            name='education_level',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='residence',
        ),
    ]
