# Generated by Django 5.2.17 on 2026-09-17 03:55

from django.db import migrations, models


DEFAULT_PROFESSIONS = [
    "Accountant / Finance / Banking",
    "Architect / Interior Designer",
    "Business Owner / Entrepreneur",
    "Civil Servant / Public Officer",
    "Driver / Logistics / Transport",
    "Electrician / Technician / Artisan",
    "Engineer / IT / Software Developer",
    "Farmer / Agriculture / Agribusiness",
    "Healthcare / Doctor / Clinical Officer",
    "Healthcare / Nurse / Midwife",
    "Homemaker",
    "Human Resources / Administration",
    "Lawyer / Legal Practitioner",
    "Marketing / Sales / PR",
    "Mason / Builder / Contractor",
    "Media / Journalist / Photographer",
    "Pastor / Evangelist / Church Minister",
    "Pharmacist / Lab Technologist",
    "Security Officer / Police / Military",
    "Student / Scholar",
    "Tailor / Fashion Designer",
    "Teacher / Lecturer / Educator",
    "Other",
]


def seed_default_professions(apps, schema_editor):
    Profession = apps.get_model('members', 'Profession')
    for name in DEFAULT_PROFESSIONS:
        Profession.objects.get_or_create(name=name, defaults={'is_default': True})


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0051_remove_memberprofile_education_level_marital_status_residence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('is_default', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(seed_default_professions, migrations.RunPython.noop),
    ]
