# Generated by Django 5.2.17 on 2026-09-17 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0052_profession'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('meeting_date', models.DateField()),
                ('location', models.CharField(blank=True, default='Main Sanctuary', max_length=160)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('completed', 'Completed'), ('archived', 'Archived')], default='upcoming', max_length=20)),
                ('minutes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-meeting_date'],
            },
        ),
        migrations.AlterField(
            model_name='announcement',
            name='is_popup',
            field=models.BooleanField(default=False, help_text='Pop up automatically to users requiring action'),
        ),
        migrations.CreateModel(
            name='BusinessMeetingAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=1)),
                ('document', models.FileField(blank=True, null=True, upload_to='business-meeting-docs/')),
                ('document_name', models.CharField(blank=True, default='', max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendas', to='members.businessmeeting')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
