# Generated by Django 5.2.17 on 2026-09-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0054_remove_adventist_muslim_relations_giving_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchsettings',
            name='default_receipt_message',
            field=models.TextField(blank=True, default='Thank you for your faithful contribution to Loma Linda SDA Church. May God bless you abundantly!'),
        ),
    ]
