# Generated by Django 5.2.17 on 2026-09-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0055_churchsettings_default_receipt_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashcontribution',
            name='giver_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='cashcontribution',
            name='giver_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='cashcontribution',
            name='receipt_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
