# Generated by Django 5.2.17 on 2026-09-18 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0057_boardmeeting_enhancements_and_churchsettings_invitations'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashcontribution',
            name='entry_type',
            field=models.CharField(choices=[('individual', 'Individual Member'), ('anonymous', 'Anonymous Giver'), ('collection', 'General Collection')], default='individual', max_length=20),
        ),
        migrations.AddField(
            model_name='cashcontribution',
            name='item_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='cashcontribution',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('in_kind', 'In-Kind'), ('mpesa', 'M-Pesa'), ('card', 'Card')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='cashcontribution',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
