# Generated by Django 5.2.17 on 2026-09-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0059_rename_giving_purposes_max_two_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashcontribution',
            name='purpose',
            field=models.CharField(default='Combined Offering', max_length=120),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='purpose',
            field=models.CharField(default='Combined Offering', max_length=120),
        ),
    ]
