# Generated by Django 5.2.17 on 2026-09-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0060_alter_cashcontribution_purpose_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='sharing_option',
            field=models.CharField(blank=True, default='site', max_length=100),
        ),
    ]
