# Generated by Django 5.2.17 on 2026-09-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0061_alter_announcement_sharing_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchsettings',
            name='conference',
            field=models.CharField(blank=True, default='East Africa Division', help_text='SDA Conference/Division name', max_length=160),
        ),
        migrations.AddField(
            model_name='churchsettings',
            name='district',
            field=models.CharField(blank=True, help_text='NEKF district name, e.g. "Meru Central"', max_length=160),
        ),
        migrations.AddField(
            model_name='churchsettings',
            name='field',
            field=models.CharField(blank=True, default='North East Kenya Field', help_text='SDA Field name, e.g. "North East Kenya Field"', max_length=160),
        ),
    ]
