# Generated by Django 5.2.17 on 2026-09-18 16:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0064_update_receipt_message_wording'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TreasuryAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('account_number', models.CharField(blank=True, default='', max_length=80)),
                ('account_type', models.CharField(choices=[('bank', 'Bank Account'), ('mobile_money', 'Mobile Money / Paybill'), ('cash', 'Cash / Petty Cash'), ('other', 'Other Account')], default='bank', max_length=30)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='churchsettings',
            name='default_receipt_message',
            field=models.TextField(blank=True, default='Thank you, {name}, for contributing {amount} towards {purpose}. May God bless you abundantly!'),
        ),
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('category', models.CharField(choices=[('operations', 'Church Operations'), ('evangelism', 'Evangelism & Missions'), ('utilities', 'Utilities (Water, Power, Net)'), ('maintenance', 'Maintenance & Repairs'), ('welfare', 'Welfare & Assistance'), ('sabbath_school', 'Sabbath School Materials'), ('building', 'Building & Development'), ('other', 'Other Expenditure')], default='operations', max_length=40)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa / Mobile'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque')], default='cash', max_length=30)),
                ('vendor_payee', models.CharField(blank=True, default='', max_length=160)),
                ('receipt_number', models.CharField(blank=True, default='', max_length=80)),
                ('expenditure_date', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenditures', to='members.treasuryaccount')),
            ],
            options={
                'ordering': ['-expenditure_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TreasuryAccountTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit (Deposit / Inflow)'), ('debit', 'Debit (Expenditure / Outflow)'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('description', models.CharField(max_length=255)),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='members.treasuryaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('related_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_transactions', to='members.treasuryaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
