# Generated by Django 5.2.17 on 2026-09-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0065_treasuryaccount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchsettings',
            name='bank_account_name',
            field=models.CharField(blank=True, default='SDA Church Main Account', max_length=160),
        ),
        migrations.AddField(
            model_name='churchsettings',
            name='bank_account_number',
            field=models.CharField(blank=True, default='1122334455', max_length=80),
        ),
        migrations.AddField(
            model_name='churchsettings',
            name='bank_branch',
            field=models.CharField(blank=True, default='Meru', max_length=120),
        ),
        migrations.AddField(
            model_name='churchsettings',
            name='bank_name',
            field=models.CharField(blank=True, default='KCB Bank Kenya', max_length=160),
        ),
        migrations.AddField(
            model_name='churchsettings',
            name='bank_paybill_number',
            field=models.CharField(blank=True, default='522522', max_length=50),
        ),
        migrations.AddField(
            model_name='churchsettings',
            name='bank_swift_code',
            field=models.CharField(blank=True, default='KCBKNEN', max_length=50),
        ),
    ]
