# Generated by Django 5.2.17 on 2026-09-19 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0066_churchsettings_bank_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='is_disfellowshipped',
            field=models.BooleanField(default=False, help_text='Whether the member has been disfellowshipped'),
        ),
    ]
