# Generated by Django 5.2.17 on 2026-09-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0068_membershiptransferrequest_remain_friend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('bank_transfer', 'Bank-to-Bank Transfer'), ('cheque', 'Cheque'), ('cash', 'Cash')], default='mpesa', max_length=20),
        ),
        migrations.AlterField(
            model_name='cashcontribution',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('in_kind', 'In-Kind'), ('mpesa', 'M-Pesa'), ('bank_transfer', 'Bank-to-Bank Transfer')], default='cash', max_length=20),
        ),
    ]
