# Generated by Django 5.2.17 on 2026-09-19

from django.db import migrations, models


def remove_in_kind_contributions(apps, schema_editor):
    """Delete legacy in-kind demo contributions (in-kind giving has been retired)."""
    Contribution = apps.get_model('members', 'Contribution')
    Contribution.objects.filter(giving_type='in_kind').delete()
    CashContribution = apps.get_model('members', 'CashContribution')
    CashContribution.objects.filter(payment_method='in_kind').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0069_alter_contribution_payment_method_and_more'),
    ]

    operations = [
        migrations.RunPython(remove_in_kind_contributions, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='cashcontribution',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('bank_transfer', 'Bank-to-Bank Transfer')], default='cash', max_length=20),
        ),
    ]
