# Generated by Django 5.2.17 on 2026-09-19

from django.db import migrations


def consolidate_lcb(apps, schema_editor):
    """Fold the LCB purpose into 'Local Church Budget' (same fund, clearer name)."""
    GivingPurpose = apps.get_model('members', 'GivingPurpose')
    Contribution = apps.get_model('members', 'Contribution')
    CashContribution = apps.get_model('members', 'CashContribution')

    # 1. Ensure the canonical purpose exists
    gp, _ = GivingPurpose.objects.get_or_create(
        name='Local Church Budget',
        defaults={'account_name': 'local_church_budget', 'active': True},
    )
    if not gp.active:
        gp.active = True
        gp.save(update_fields=['active'])
    if gp.account_name != 'local_church_budget':
        gp.account_name = 'local_church_budget'
        gp.save(update_fields=['account_name'])

    # 2. Move contributions onto the canonical name
    for old in ('LCB', 'Lcb', 'lcb'):
        Contribution.objects.filter(purpose=old).update(purpose='Local Church Budget')
        CashContribution.objects.filter(purpose=old).update(purpose='Local Church Budget')

    # 3. Deactivate the redundant purpose rows
    GivingPurpose.objects.filter(name__in=['LCB', 'Lcb', 'Local Church Budget (LCB)']).update(active=False)


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0071_bank_to_bank_label'),
    ]

    operations = [
        migrations.RunPython(consolidate_lcb, migrations.RunPython.noop),
    ]
