# Generated by Django 5.2.17 on 2026-09-20 01:47

from django.db import migrations, models


def backfill_roles_from_role(apps, schema_editor):
    """Seed the new multi-role field from each profile's existing single role."""
    MemberProfile = apps.get_model('members', 'MemberProfile')
    for profile in MemberProfile.objects.exclude(role='member').exclude(role=''):
        if not profile.roles or profile.roles == 'member':
            profile.roles = profile.role
            profile.save(update_fields=['roles'])


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0072_consolidate_lcb_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='baptismal_status',
            field=models.CharField(blank=True, choices=[('baptised', 'Baptised'), ('not_baptised', 'Not Baptised'), ('transfer_pending', 'Transfer In Progress')], help_text='Baptismal status (mainly for friends)', max_length=30),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='current_church',
            field=models.CharField(blank=True, help_text='Church the person currently attends (mainly for friends)', max_length=160),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='roles',
            field=models.CharField(blank=True, default='member', help_text='Comma-separated role codes; a member can hold several roles', max_length=250),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='giving_type',
            field=models.CharField(choices=[('financial', 'Financial')], default='financial', max_length=20),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('clerk', 'Church Clerk'), ('elder', 'Elder / First Elder'), ('youth_leader', 'Youth Leader'), ('choir_director', 'Choir Director'), ('children_ministry', 'Children Leader'), ('men_ministry', 'AMM Leader'), ('women_ministry', 'AWM Leader'), ('chaplaincy', 'Chaplain'), ('finance', 'Finance Team'), ('treasurer', 'Treasurer'), ('leader', 'Church Leader'), ('admin', 'Administrator')], default='member', help_text="Primary/legacy role kept in sync with 'roles'", max_length=30),
        ),
        migrations.RunPython(backfill_roles_from_role, migrations.RunPython.noop),
    ]
