# Generated by Django 5.2.17 on 2026-09-20 03:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0073_memberprofile_baptismal_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InKindContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(blank=True, max_length=160)),
                ('donor_email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('items', models.TextField(help_text='Donated items, one per row')),
                ('purpose', models.CharField(default='In-Kind Offering', max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('received_on', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='in_kind_contributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'in-kind contributions',
                'ordering': ['-created_at'],
            },
        ),
    ]
