# Generated by Django 5.2.17 on 2026-09-21 09:25

from django.db import migrations, models

OLD_DEFAULT = 'Loma Linda SDA Church, Meru'
NEW_NAME = 'SDA Loma Linda Meru'


def rename_the_church(apps, schema_editor):
    """Rename churches still sitting on the old default name.

    A name the office chose itself (anything that is not exactly the old
    default) is left alone.
    """
    ChurchSettings = apps.get_model('members', 'ChurchSettings')
    ChurchSettings.objects.filter(church_name=OLD_DEFAULT).update(church_name=NEW_NAME)


def restore_the_old_name(apps, schema_editor):
    ChurchSettings = apps.get_model('members', 'ChurchSettings')
    ChurchSettings.objects.filter(church_name=NEW_NAME).update(church_name=OLD_DEFAULT)


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0076_administrators_full_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchsettings',
            name='church_name',
            field=models.CharField(default=NEW_NAME, max_length=160),
        ),
        migrations.RunPython(rename_the_church, restore_the_old_name),
    ]
