# Generated by Django 5.2.17 on 2026-09-21 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0082_invitation_token_hash_and_link_lifetime'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted by M-Pesa'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('outcome_description', models.CharField(blank=True, max_length=255)),
                ('originator_conversation_id', models.CharField(max_length=64, unique=True)),
                ('conversation_id', models.CharField(blank=True, max_length=64)),
                ('transaction_id', models.CharField(blank=True, max_length=64)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contribution', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='refund', to='members.contribution')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mpesa_refunds_initiated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
