# Generated by Django 5.2.17 on 2026-09-21 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0083_mpesa_refund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesarefund',
            name='contribution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='members.contribution'),
        ),
    ]
