# Generated by Django 5.2.17 on 2026-09-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0091_receipt_message_greeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('clerk', 'Church Clerk'), ('elder', 'Elder / First Elder'), ('youth_leader', 'Youth Leader'), ('choir_director', 'Choir Director'), ('children_ministry', 'Children Leader'), ('men_ministry', 'AMM Leader'), ('women_ministry', 'AWM Leader'), ('chaplaincy', 'Chaplain'), ('finance', 'Finance Team'), ('treasurer', 'Treasurer'), ('admin', 'Administrator')], default='member', help_text="Primary/legacy role kept in sync with 'roles'", max_length=30),
        ),
    ]
