# Generated by Django 5.2.17 on 2026-09-23 00:25

from django.db import migrations, models
from django.utils import timezone


def expire_stale_invitations(apps, schema_editor):
    """Pending invitations whose link already stopped working are expired.

    The link was dead the moment ``expires_at`` passed, but the rows kept
    saying "pending", so the admin console's Pending list filled up with
    invitations nobody could ever accept.
    """
    Invitation = apps.get_model('members', 'Invitation')
    Invitation.objects.filter(status='pending', expires_at__lte=timezone.now()).update(status='expired')


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0092_alter_memberprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
        migrations.RunPython(expire_stale_invitations, migrations.RunPython.noop),
    ]
