# Generated by Django 5.2.17 on 2026-09-23 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0093_invitation_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='event_date_from',
            field=models.DateField(blank=True, help_text='First day of the event this announcement is about', null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='event_date_to',
            field=models.DateField(blank=True, help_text='Last day of that event; same as from, or blank, for a single day', null=True),
        ),
    ]
