# Generated by Django 5.2.17 on 2026-09-23 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0094_announcement_event_dates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tag_number', models.CharField(blank=True, default='', max_length=80)),
                ('category', models.CharField(choices=[('audio_visual', 'Audio/Visual'), ('furniture', 'Furniture'), ('sacramental', 'Sacramental'), ('kitchen', 'Kitchen'), ('electronics', 'Electronics'), ('general', 'General')], default='general', max_length=40)),
                ('location', models.CharField(blank=True, default='', max_length=160)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('state', models.CharField(choices=[('good', 'Good'), ('in_use', 'In Use'), ('needs_repair', 'Needs Repair'), ('damaged', 'Damaged'), ('retired', 'Retired')], default='good', max_length=30)),
                ('assigned_to', models.CharField(blank=True, default='', max_length=160)),
                ('checked_out_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('last_inspected_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items_registered', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('check_out', 'Check Out'), ('check_in', 'Check In'), ('state_change', 'State Change')], max_length=20)),
                ('moved_by', models.CharField(max_length=160)),
                ('destination', models.CharField(blank=True, default='', max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('state_after', models.CharField(blank=True, choices=[('good', 'Good'), ('in_use', 'In Use'), ('needs_repair', 'Needs Repair'), ('damaged', 'Damaged'), ('retired', 'Retired')], default='', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='members.inventoryitem')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
