# Generated by Django 5.2.17 on 2026-09-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0095_inventory_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardmeeting',
            name='meeting_time',
        ),
        migrations.RemoveField(
            model_name='boardmeeting',
            name='reference_file',
        ),
        migrations.AddField(
            model_name='boardmeeting',
            name='end_time',
            field=models.TimeField(blank=True, help_text='When the meeting is expected to end', null=True),
        ),
        migrations.AddField(
            model_name='boardmeeting',
            name='start_time',
            field=models.TimeField(blank=True, help_text='When the meeting starts', null=True),
        ),
        migrations.AlterField(
            model_name='churchsettings',
            name='default_board_meeting_invitation_message',
            field=models.TextField(blank=True, default='{greeting}, {name}. {church} is inviting you to a board meeting scheduled for {day}, {date} from {start_time} to {end_time}. God bless you as you purpose to attend.'),
        ),
        migrations.AlterField(
            model_name='churchsettings',
            name='default_business_meeting_invitation_message',
            field=models.TextField(blank=True, default='{greeting}, {name}. {church} is inviting you to a church business meeting scheduled for {day}, {date} at {meeting_time}, {location}. God bless you as you purpose to attend.'),
        ),
    ]
