# Generated by Django 5.2.17 on 2026-09-23 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0097_meeting_invitation_wording'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='payment_group',
            field=models.UUIDField(blank=True, db_index=True, help_text='Groups the account lines of a single payment when a giver split one gift.', null=True),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='checkout_request_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='mpesa_receipt_number',
            field=models.CharField(blank=True, help_text="Safaricom's code; shared by the account lines of one split payment.", max_length=64, null=True),
        ),
    ]
