# Generated by Django 5.2.17 on 2026-09-23 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0098_contribution_payment_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchsettings',
            name='dashboard_encouragement_line',
            field=models.CharField(blank=True, default='Jesus is coming again.', help_text='Short encouragement shown under the dashboard greeting (140 characters).', max_length=140),
        ),
    ]
