# Generated by Django 5.2.17 on 2026-09-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0099_dashboard_encouragement_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchsettings',
            name='privacy_policy',
            field=models.TextField(blank=True, help_text="The church's own privacy policy. Shown on /privacy when set."),
        ),
        migrations.AddField(
            model_name='churchsettings',
            name='terms_of_use',
            field=models.TextField(blank=True, help_text="The church's own terms of use. Shown on /terms when set."),
        ),
    ]
