# Generated by Django 5.2.17 on 2026-09-23 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0100_church_legal_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='campaign',
            field=models.ForeignKey(blank=True, help_text='Set when this announcement is the public face of a fund drive.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='members.fundraisingcampaign'),
        ),
        migrations.AddField(
            model_name='fundraisingcampaign',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='campaign-attachments/'),
        ),
        migrations.AlterField(
            model_name='treasuryaccount',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Shown in the giving form and reports (e.g. "Tithe — returned to God for gospel work").', max_length=160),
        ),
        migrations.AlterField(
            model_name='treasuryaccount',
            name='name',
            field=models.CharField(help_text='The account, as M-Pesa shows it in the prompt. Safaricom caps the account reference at 12 characters, so the name must be short.', max_length=12),
        ),
    ]
