# Generated by Django 5.2.17 on 2026-09-23 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0102_short_treasury_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changes', models.JSONField(help_text='Field-by-field proposed values for the profile.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('kept', 'Member kept their details')], default='pending', max_length=20)),
                ('proposed_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(help_text='The member whose profile is proposed to change.', on_delete=django.db.models.deletion.CASCADE, related_name='profile_change_requests', to=settings.AUTH_USER_MODEL)),
                ('proposed_by', models.ForeignKey(help_text='The administrator or clerk who proposed the change.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_changes_proposed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-proposed_at'],
            },
        ),
    ]
