# Generated by Django 5.2.17 on 2026-09-23 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0104_seed_legal_documents'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GivingPurpose',
        ),
    ]
