# Generated by Django 5.2.17 on 2026-09-24 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0106_church_roles_and_assistants'),
        ('members', '0106_memberprofile_ministry_and_more'),
    ]

    operations = [
    ]
