# Generated by Django 5.2.17 on 2026-09-24 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0108_memberprofile_residence'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentrequest',
            name='residence',
            field=models.CharField(blank=True, default='', help_text='Where the person lives — estate, street or town', max_length=160),
        ),
    ]
