# Generated by Django 5.2.17 on 2026-09-24 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0109_enrollmentrequest_residence'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchsettings',
            name='mpesa_account_name',
            field=models.CharField(blank=True, default='', help_text='Name registered on the M-Pesa receiving account', max_length=160),
        ),
        migrations.AddField(
            model_name='churchsettings',
            name='mpesa_account_number',
            field=models.CharField(blank=True, default='', help_text='Account number members type in the M-Pesa prompt (e.g. TITHE)', max_length=60),
        ),
        migrations.AddField(
            model_name='churchsettings',
            name='mpesa_paybill_number',
            field=models.CharField(blank=True, default='', help_text='Pay Bill number members send money to (leave blank to hide)', max_length=20),
        ),
        migrations.AddField(
            model_name='churchsettings',
            name='mpesa_phone_number',
            field=models.CharField(blank=True, default='', help_text='Phone number for Send Money instructions (leave blank to hide)', max_length=20),
        ),
    ]
