# Generated by Django 5.2.17 on 2026-09-24 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0110_churchsettings_mpesa_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundraisingcampaign',
            name='allow_personal_invitations',
            field=models.BooleanField(default=False, help_text='Whether members may be issued personal invite links for this drive'),
        ),
    ]
