# Generated by Django 5.2.17 on 2026-09-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0111_campaign_personal_invites'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchsettings',
            name='role_rights',
            field=models.JSONField(blank=True, default=dict, help_text='Rights per role: {role_code: [right_code, ...]}'),
        ),
        migrations.AlterField(
            model_name='churchsettings',
            name='board_roles',
            field=models.JSONField(blank=True, default=list, help_text='Deprecated: the board is every role holder now. Kept only so old rows load.'),
        ),
    ]
