# Generated by Django 5.2.17 on 2026-09-24 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0112_role_rights'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='churchsettings',
            name='board_roles',
        ),
    ]
