# Generated by Django 5.2.17 on 2026-09-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0113_drop_board_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentrequest',
            name='joining_mode',
            field=models.CharField(choices=[('baptism', 'Baptism'), ('membership_transfer', 'Membership transfer'), ('friend', 'Friend of SDA Loma Linda'), ('sabbath_school', 'Sabbath School')], default='baptism', max_length=30),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='account_type',
            field=models.CharField(choices=[('member', 'Member'), ('friend', 'Friend of SDA Loma Linda'), ('sabbath_school', 'Sabbath School')], default='member', max_length=20),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='account_type',
            field=models.CharField(choices=[('member', 'Member'), ('friend', 'Friend of SDA Loma Linda'), ('sabbath_school', 'Sabbath School')], default='member', max_length=20),
        ),
    ]
