# Generated by Django 5.2.17 on 2026-09-25 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0114_remove_churchsettings_role_rights_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='starts_at',
            field=models.DateField(blank=True, help_text='Date from which the announcement starts being displayed', null=True),
        ),
    ]
