# Generated by Django 5.2.17 on 2026-09-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0116_invitation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchsettings',
            name='default_membership_approval_message',
            field=models.TextField(blank=True, default='Dear {name},\n\nYour request to join {church} has been approved. You can now sign in at {link} to take part in the life of the church.\n\nGod bless you.'),
        ),
        migrations.AddField(
            model_name='churchsettings',
            name='default_request_notification_message',
            field=models.TextField(blank=True, default='{greeting}, {user_name} has submitted a {request}. Log in to respond to it: {link}'),
        ),
    ]
