# Generated by Django 5.2.17 on 2026-09-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0117_request_notification_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='audience',
            field=models.JSONField(blank=True, default=list, help_text='Ministry role codes this post addresses; empty means the whole congregation'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='expires_at',
            field=models.DateField(blank=True, help_text='Legacy display end; the event date drives ordering and dismissal now', null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='starts_at',
            field=models.DateField(blank=True, help_text='Legacy display start; the event date drives ordering and dismissal now', null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='visibility',
            field=models.CharField(choices=[('members_only', 'Members only'), ('public_website', 'Public website'), ('all', 'Everyone')], default='members_only', max_length=20),
        ),
    ]
