# Generated by Django 5.2.17 on 2026-09-26 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0119_rename_announcement_visibility_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='support_account',
            field=models.CharField(blank=True, default='', help_text='Treasury account this post invites support for', max_length=80),
        ),
    ]
