# Generated by Django 5.2.17 on 2026-09-26 05:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0120_announcement_support_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Member'), ('clerk', 'Church Clerk'), ('elder', 'Elder'), ('first_elder', 'First Elder'), ('second_elder', 'Second Elder'), ('third_elder', 'Third Elder'), ('head_deacon', 'Head Deacon'), ('head_deaconess', 'Head Deaconess'), ('treasurer', 'Treasurer'), ('pm_leader', 'PM Leader'), ('apm_leader', 'APM Leader'), ('men_ministry', 'AMM Leader'), ('women_ministry', 'AWM Leader'), ('youth_leader', 'Youth Leader'), ('chaplaincy', 'Chaplaincy Leader'), ('children_ministry', 'Children Leader'), ('health_leader', 'Health Leader'), ('ambassadors_leader', 'Ambassadors Leader'), ('education_leader', 'Education Leader'), ('family_life', 'Family Life'), ('pathfinders_leader', 'Pathfinders Leader'), ('adventurers_leader', 'Adventurers Leader'), ('publishing_head', 'Publishing Head'), ('welfare_leader', 'Welfare Leader'), ('interest_coordinator', 'Interest Coordinator'), ('development', 'Development'), ('choir_director', 'Choir Director'), ('admin', 'Administrator')], max_length=30)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, help_text='Blank while the member still holds the role', null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-started_at',),
                'indexes': [models.Index(fields=['member', 'role'], name='members_rol_member__62aa78_idx')],
            },
        ),
    ]
