# Generated by Django 5.2.17 on 2026-09-26 17:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0123_split_receipt_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('amm', 'Adventist Men Ministries (AMM)'), ('awm', 'Adventist Women Ministries (AWM)'), ('aym', 'Adventist Youth & Children (AYM)'), ('apm', 'Adventist Possibility Ministries (APM)'), ('chaplaincy', 'Chaplaincy Ministry')], max_length=30)),
                ('title', models.CharField(max_length=160)),
                ('event_date', models.DateField()),
                ('event_time', models.CharField(blank=True, help_text="Free-text, e.g. '09:00 AM' or 'during divine service'", max_length=20)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('lead', models.CharField(blank=True, help_text='Who leads the event; blank means the department itself', max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_events_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('event_date', 'event_time', 'title'),
                'indexes': [models.Index(fields=['department', 'event_date'], name='members_dep_departm_37b8a5_idx')],
            },
        ),
        migrations.CreateModel(
            name='DepartmentMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('amm', 'Adventist Men Ministries (AMM)'), ('awm', 'Adventist Women Ministries (AWM)'), ('aym', 'Adventist Youth & Children (AYM)'), ('apm', 'Adventist Possibility Ministries (APM)'), ('chaplaincy', 'Chaplaincy Ministry')], max_length=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_memberships_added', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
                'constraints': [models.UniqueConstraint(fields=('member', 'department'), name='uniq_member_per_department')],
            },
        ),
    ]
