# Generated by Django 5.2.17 on 2026-09-27 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0124_departmentevent_departmentmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchnotification',
            name='link',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
