# Generated by Django 5.2.17 on 2026-09-27 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0127_memberprofile_announce_email_announce_push'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchsettings',
            name='vapid_private_key',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
