# Generated by Django 5.2.17 on 2026-09-27 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0128_alter_churchsettings_vapid_private_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='announcement_type',
            field=models.CharField(choices=[('awareness', 'Awareness'), ('web_conference', 'Web conference'), ('promotion', 'Promotion / Contribution')], default='awareness', help_text='Awareness is a plain notice; web conference carries a link; promotion invites support for an account', max_length=30),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('clerk', 'Church Clerk'), ('elder', 'Elder'), ('first_elder', 'First Elder'), ('second_elder', 'Second Elder'), ('third_elder', 'Third Elder'), ('pastor', 'Church Pastor'), ('head_deacon', 'Head Deacon'), ('head_deaconess', 'Head Deaconess'), ('treasurer', 'Treasurer'), ('pm_leader', 'PM Leader'), ('apm_leader', 'APM Leader'), ('men_ministry', 'AMM Leader'), ('women_ministry', 'AWM Leader'), ('youth_leader', 'Youth Leader'), ('chaplaincy', 'Chaplaincy Leader'), ('children_ministry', 'Children Leader'), ('health_leader', 'Health Leader'), ('ambassadors_leader', 'Ambassadors Leader'), ('education_leader', 'Education Leader'), ('family_life', 'Family Life'), ('pathfinders_leader', 'Pathfinders Leader'), ('adventurers_leader', 'Adventurers Leader'), ('publishing_head', 'Publishing Head'), ('welfare_leader', 'Welfare Leader'), ('interest_coordinator', 'Interest Coordinator'), ('development', 'Development'), ('choir_director', 'Choir Director'), ('admin', 'Administrator')], default='member', help_text="Primary/legacy role kept in sync with 'roles'", max_length=30),
        ),
        migrations.AlterField(
            model_name='rolehistory',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('clerk', 'Church Clerk'), ('elder', 'Elder'), ('first_elder', 'First Elder'), ('second_elder', 'Second Elder'), ('third_elder', 'Third Elder'), ('pastor', 'Church Pastor'), ('head_deacon', 'Head Deacon'), ('head_deaconess', 'Head Deaconess'), ('treasurer', 'Treasurer'), ('pm_leader', 'PM Leader'), ('apm_leader', 'APM Leader'), ('men_ministry', 'AMM Leader'), ('women_ministry', 'AWM Leader'), ('youth_leader', 'Youth Leader'), ('chaplaincy', 'Chaplaincy Leader'), ('children_ministry', 'Children Leader'), ('health_leader', 'Health Leader'), ('ambassadors_leader', 'Ambassadors Leader'), ('education_leader', 'Education Leader'), ('family_life', 'Family Life'), ('pathfinders_leader', 'Pathfinders Leader'), ('adventurers_leader', 'Adventurers Leader'), ('publishing_head', 'Publishing Head'), ('welfare_leader', 'Welfare Leader'), ('interest_coordinator', 'Interest Coordinator'), ('development', 'Development'), ('choir_director', 'Choir Director'), ('admin', 'Administrator')], max_length=30),
        ),
    ]
