# Generated by Django 5.2.17 on 2026-09-27 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0129_announcement_announcement_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentrequest',
            name='code',
            field=models.CharField(blank=True, default='', editable=False, help_text='SHA-256 hash of the short verification code emailed to the person', max_length=64, unique=True),
        ),
    ]
