# Generated by Django 5.2.17 on 2026-09-27 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0130_enrollmentrequest_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='response_mode',
            field=models.CharField(blank=True, choices=[('open', 'Open response'), ('closed', 'Closed response')], default='open', help_text='Opinion posts only: open text answers, or a choice among fixed options', max_length=10),
        ),
        migrations.AddField(
            model_name='announcement',
            name='response_options',
            field=models.TextField(blank=True, default='', help_text='Opinion posts with closed responses: one option per line, exactly as members will see them'),
        ),
        migrations.AddField(
            model_name='announcementresponse',
            name='response_choice',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='announcement_type',
            field=models.CharField(choices=[('awareness', 'Awareness'), ('web_conference', 'Web conference'), ('promotion', 'Promotion / Contribution'), ('opinion', 'Opinion')], default='awareness', help_text='Awareness is a plain notice; web conference carries a link; promotion invites support for an account; opinion asks for responses', max_length=30),
        ),
    ]
