# Generated by Django 5.2.17 on 2026-09-27 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0131_announcement_response_mode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('amm', 'Adventist Men Ministries (AMM)'), ('awm', 'Adventist Women Ministries (AWM)'), ('aym', 'Adventist Youth & Children (AYM)'), ('apm', 'Adventist Possibility Ministries (APM)'), ('chaplaincy', 'Chaplaincy Ministry')], max_length=30)),
                ('year', models.PositiveIntegerField()),
                ('title', models.CharField(help_text="What the money is for, e.g. 'Camp fees subsidy'", max_length=160)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_budgets_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-year', 'title'),
                'constraints': [models.UniqueConstraint(fields=('department', 'year', 'title'), name='unique_department_budget_line')],
            },
        ),
    ]
