# Generated by Django 5.2.17 on 2026-09-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0132_departmentbudget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='announcement_type',
            field=models.CharField(choices=[('awareness', 'Awareness'), ('web_conference', 'Web conference'), ('promotion', 'Promotion / Contribution'), ('opinion', 'Opinion poll')], default='awareness', help_text='Awareness is a plain notice; web conference carries a link; promotion invites support for an account; an opinion poll asks for responses', max_length=30),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='response_mode',
            field=models.CharField(blank=True, choices=[('open', 'Open response'), ('closed', 'Closed response')], default='open', help_text='Opinion polls only: open text answers, or a choice among fixed options', max_length=10),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='response_options',
            field=models.TextField(blank=True, default='', help_text='Opinion polls with closed responses: one option per line, exactly as members will see them'),
        ),
    ]
