# Generated by Django 5.2.17 on 2026-09-27 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0133_alter_announcement_announcement_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='churchsettings',
            name='dashboard_encouragement_line',
        ),
    ]
