# Generated by Django 5.2.17 on 2026-09-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0137_enrollment_joining_mode_transfer_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentbudget',
            name='department',
            field=models.CharField(choices=[('amm', 'Adventist Men Ministries (AMM)'), ('awm', 'Adventist Women Ministries (AWM)'), ('aym', 'Adventist Youth (AYM)'), ('children', 'Children Ministry'), ('ambassadors', 'Ambassadors'), ('apm', 'Adventist Possibility Ministries (APM)'), ('chaplaincy', 'Chaplaincy Ministry')], max_length=30),
        ),
        migrations.AlterField(
            model_name='departmentevent',
            name='department',
            field=models.CharField(choices=[('amm', 'Adventist Men Ministries (AMM)'), ('awm', 'Adventist Women Ministries (AWM)'), ('aym', 'Adventist Youth (AYM)'), ('children', 'Children Ministry'), ('ambassadors', 'Ambassadors'), ('apm', 'Adventist Possibility Ministries (APM)'), ('chaplaincy', 'Chaplaincy Ministry')], max_length=30),
        ),
        migrations.AlterField(
            model_name='departmentmembership',
            name='department',
            field=models.CharField(choices=[('amm', 'Adventist Men Ministries (AMM)'), ('awm', 'Adventist Women Ministries (AWM)'), ('aym', 'Adventist Youth (AYM)'), ('children', 'Children Ministry'), ('ambassadors', 'Ambassadors'), ('apm', 'Adventist Possibility Ministries (APM)'), ('chaplaincy', 'Chaplaincy Ministry')], max_length=30),
        ),
    ]
