# Generated by Django 5.2.17 on 2026-09-28 16:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


# Mirrors SEED_AREAS in members.models — migrations cannot import app code.
SEED_AREAS = (
    ('church', 'The Church', 'church', 0),
    ('eldership', 'Eldership', 'office', 1),
    ('clerkship', 'Clerkship', 'office', 2),
    ('deaconate', 'Deaconate', 'office', 3),
    ('amm', 'Adventist Men Ministries (AMM)', 'department', 10),
    ('awm', 'Adventist Women Ministries (AWM)', 'department', 11),
    ('aym', 'Adventist Youth (AYM)', 'department', 12),
    ('children', 'Children Ministry', 'department', 13),
    ('ambassadors', 'Ambassadors', 'department', 14),
    ('apm', 'Adventist Possibility Ministries (APM)', 'department', 15),
    ('chaplaincy', 'Chaplaincy Ministry', 'department', 16),
)

SEED_AREA_ROLES = {
    'church': (
        'First Elder', 'Elder', 'Church Clerk', 'Church Treasurer', 'Head Deacon',
        'Head Deaconess', 'PM Leader', 'AWM Leader', 'AYM Leader', 'Children Leader',
        'Ambassadors Leader', 'APM Leader', 'Chaplaincy Leader', 'Health Leader',
        'Education Leader', 'Family Life Leader', 'Publishing Head', 'Welfare Leader',
        'Interest Coordinator', 'Development', 'Choir Director',
    ),
    'eldership': ('First Elder', 'Second Elder', 'Third Elder'),
    'clerkship': ('Church Clerk',),
    'deaconate': ('Head Deacon', 'Head Deaconess'),
}

DEFAULT_POSITIONS = ('Leader', 'Assistant', 'Secretary', 'Treasurer')


def seed_areas(apps, schema_editor):
    """Create the seeded areas with their offices, and fill department
    offices from the role flags the old system carried.

    The church and office areas start empty (the desk appoints into them);
    department offices are backfilled: the first holder of the department's
    old lead role becomes Leader, holders flagged as assistants on that role
    take Assistant, a third holder takes Secretary. Nobody loses any service
    they were already doing.
    """
    LeadershipArea = apps.get_model('members', 'LeadershipArea')
    AreaRole = apps.get_model('members', 'AreaRole')
    MemberProfile = apps.get_model('members', 'MemberProfile')

    lead_roles = {
        'amm': 'men_ministry', 'awm': 'women_ministry', 'aym': 'youth_leader',
        'children': 'children_ministry', 'ambassadors': 'ambassadors_leader',
        'apm': 'apm_leader', 'chaplaincy': 'chaplaincy',
    }
    profiles = list(
        MemberProfile.objects.select_related('user')
        .filter(user__is_active=True)
        .order_by('pk')
    )
    for code, name, kind, sort in SEED_AREAS:
        if LeadershipArea.objects.filter(code=code).exists():
            continue
        area = LeadershipArea.objects.create(code=code, name=name, kind=kind, sort_order=sort)
        titles = list(SEED_AREA_ROLES.get(code, DEFAULT_POSITIONS))
        rows = [AreaRole(area=area, title=title, position_order=index) for index, title in enumerate(titles)]
        if code in lead_roles:
            role_code = lead_roles[code]
            leader_done = False
            for profile in profiles:
                roles = {r.strip() for r in (profile.roles or '').split(',') if r.strip()}
                if role_code not in roles:
                    continue
                flags = {r.strip() for r in (profile.assistant_roles or '').split(',') if r.strip()}
                if not leader_done and role_code not in flags:
                    rows[0].holder = profile.user
                    leader_done = True
                elif not rows[1].holder_id:
                    rows[1].holder = profile.user
                elif not rows[2].holder_id:
                    rows[2].holder = profile.user
        for row in rows:
            row.save()


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0138_alter_departmentbudget_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadershipArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Stable identifier used in API paths and audience codes', max_length=60, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('kind', models.CharField(choices=[('church', 'The church'), ('office', 'Church office'), ('department', 'Department / ministry')], default='department', max_length=20)),
                ('icon', models.CharField(blank=True, help_text='Lucide icon name shown beside the area', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Stable identifier used by permissions and audiences', max_length=60, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('is_system', models.BooleanField(default=False, help_text='Seeded role the church runs on; protected from deletion')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='departmentbudget',
            name='department',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='departmentevent',
            name='department',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='departmentmembership',
            name='department',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='AreaRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('position_order', models.PositiveIntegerField(default=0)),
                ('is_custom', models.BooleanField(default=False, help_text='Added by the office beyond the seeded offices')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='area_roles', to=settings.AUTH_USER_MODEL)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='members.leadershiparea')),
            ],
            options={
                'ordering': ('position_order', 'id'),
                'constraints': [models.UniqueConstraint(fields=('area', 'title'), name='uniq_area_role_title')],
            },
        ),
        migrations.RunPython(seed_areas, migrations.RunPython.noop),
    ]
