# Generated by Django 5.2.17 on 2026-09-29 02:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


# The departments and their roles are seeded after the tables exist — the
# models carry the same registers, but migrations run against the historical
# state, so the seed is written here rather than imported. The backfill
# reads the 0139 area rows (dropped later in this same migration — RunPython
# runs after all schema operations) so today's office holders keep their
# posts as the leaders table replaces the offices.
SEED_DEPARTMENTS = (
    ('eldership', 'Eldership', 1),
    ('clerkship', 'Clerkship', 2),
    ('deaconate', 'Deaconate', 3),
    ('amm', 'Adventist Men Ministries (AMM)', 10),
    ('awm', 'Adventist Women Ministries (AWM)', 11),
    ('aym', 'Adventist Youth (AYM)', 12),
    ('children', 'Children Ministry', 13),
    ('ambassadors', 'Ambassadors', 14),
    ('apm', 'Adventist Possibility Ministries (APM)', 15),
    ('chaplaincy', 'Chaplaincy Ministry', 16),
)

SEED_DEPARTMENT_ROLES = {
    'eldership': (('First Elder', False), ('Second Elder', False), ('Third Elder', False)),
    'clerkship': (('Church Clerk', True),),
    'deaconate': (('Head Deacon', True), ('Head Deaconess', True)),
}
DEFAULT_DEPARTMENT_ROLES = (('Leader', True), ('Secretary', False), ('Treasurer', False))


def seed_departments_and_backfill(apps, schema_editor):
    """Seed the ten departments and carry over whoever held an office.

    Eldership, Clerkship and Deaconate come along as departments — the
    church itself does not: its church-wide roles return to User Management.
    The 0139 areas are read for leadership backfill: a named office keeps
    its name as the department role (Eldership's First Elder, Deaconate's
    Head Deacon), a generic Leader keeps "Leader", and an Assistant office
    becomes an assistant row on the same role. No one loses their post in
    the move.
    """
    Department = apps.get_model('members', 'Department')
    DepartmentRole = apps.get_model('members', 'DepartmentRole')
    DepartmentAssignment = apps.get_model('members', 'DepartmentAssignment')
    LeadershipArea = apps.get_model('members', 'LeadershipArea')
    AreaRole = apps.get_model('members', 'AreaRole')

    departments = {}
    roles_by_department = {}
    for code, name, sort in SEED_DEPARTMENTS:
        department, _ = Department.objects.get_or_create(
            code=code,
            defaults={'name': name, 'sort_order': sort},
        )
        departments[code] = department
        template = SEED_DEPARTMENT_ROLES.get(code, DEFAULT_DEPARTMENT_ROLES)
        roles_by_department[code] = {}
        for index, (role_name, assistant) in enumerate(template):
            role, _ = DepartmentRole.objects.get_or_create(
                department=department, name=role_name,
                defaults={'has_assistant': assistant, 'sort_order': index},
            )
            roles_by_department[code][role_name.lower()] = role

    def role_for(department_code, title):
        """The department role an office title lands in, creating it if new."""
        registry = roles_by_department[department_code]
        key = title.strip().lower()
        if key not in registry:
            role, _ = DepartmentRole.objects.get_or_create(
                department=departments[department_code], name=title.strip(),
                defaults={'sort_order': 100, 'is_custom': True},
            )
            registry[key] = role
        return registry[key]

    for area in LeadershipArea.objects.all():
        department = departments.get(area.code)
        if department is None:
            continue  # The church: its offices were church-wide roles.
        for position in AreaRole.objects.filter(area=area).order_by('position_order', 'id'):
            if not position.holder_id:
                continue
            title = position.title.strip()
            if title.lower() == 'assistant':
                # The generic assistant office becomes an assistant row on
                # the department's assistant-capable base role (Leader).
                base = next(
                    (r for r in roles_by_department[area.code].values() if r.has_assistant),
                    None,
                )
                if base is None:
                    continue
                DepartmentAssignment.objects.get_or_create(
                    role=base, member_id=position.holder_id, kind='assistant',
                    defaults={'department': department},
                )
            else:
                role = role_for(area.code, title)
                DepartmentAssignment.objects.get_or_create(
                    role=role, member_id=position.holder_id, kind='leader',
                    defaults={'department': department},
                )


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0139_roles_areas_area_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Stable identifier used in API paths and audience codes (dept_<code>)', max_length=60, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('icon', models.CharField(blank=True, help_text='Lucide icon name shown beside the department', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='DepartmentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('leader', 'Leader'), ('assistant', 'Assistant')], default='leader', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='members.department')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('role__sort_order', 'role__id', 'kind', 'id'),
            },
        ),
        migrations.CreateModel(
            name='DepartmentRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('has_assistant', models.BooleanField(default=False, help_text='The department may appoint assistants of this role beside its holder')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_custom', models.BooleanField(default=False, help_text='Added by the office beyond the seeded roles')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='members.department')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.AddField(
            model_name='departmentassignment',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='members.departmentrole'),
        ),
        # The backfill runs while the 0139 area tables still exist — it reads
        # them to carry today's office holders over. The old models are
        # deleted afterwards, whole: RemoveField on arearole.area cannot run
        # because the state's unique constraint still names the field.
        migrations.RunPython(seed_departments_and_backfill, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='AreaRole',
        ),
        migrations.DeleteModel(
            name='LeadershipArea',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.AddConstraint(
            model_name='departmentrole',
            constraint=models.UniqueConstraint(fields=('department', 'name'), name='uniq_department_role_name'),
        ),
        migrations.AddConstraint(
            model_name='departmentassignment',
            constraint=models.UniqueConstraint(fields=('role', 'member', 'kind'), name='uniq_assignment_per_role'),
        ),
    ]
