# Generated by Django 5.2.17 on 2026-09-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0149_church_event_moments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchevent',
            name='happened_on',
            field=models.DateField(blank=True, help_text='The day the event happened; orders the albums, newest first', null=True),
        ),
        migrations.AlterField(
            model_name='churchevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='churcheventmedia',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
