# Generated by Django 5.2.17 on 2026-10-01 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0152_youth_reference_aym'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='department',
            field=models.CharField(blank=True, choices=[('children', 'Children'), ('youth', 'Youth'), ('young_adults', 'Young Adults'), ('adults', 'Adults'), ('seniors', 'Seniors')], default='', help_text='Age-based department the member belongs to (exactly one)', max_length=30),
        ),
    ]
