# Generated by Django 5.2.17 on 2026-10-01 04:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0156_department_join_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='departmentjoinrequest',
            name='uniq_open_join_request_per_department',
        ),
        migrations.AddField(
            model_name='departmentjoinrequest',
            name='group_description',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='departmentjoinrequest',
            name='group_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='departmentjoinrequest',
            name='kind',
            field=models.CharField(choices=[('join', 'Join the area'), ('singing_group', 'Register a singing group')], default='join', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='departmentjoinrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'join'), ('status', 'pending')), fields=('member', 'department'), name='uniq_open_join_request_per_department'),
        ),
        migrations.AddConstraint(
            model_name='departmentjoinrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'singing_group'), ('status', 'pending')), fields=('member', 'department'), name='uniq_open_group_request_per_department'),
        ),
    ]
