# Generated by Django 5.2.17 on 2026-10-05 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0171_choir_is_ensemble'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashcontribution',
            name='payment_group',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
