# Generated by Codebuff 🤖 — do not edit by hand.
#
# Seeds the church's age- and gender-based departments with their own
# treasury accounts, so gifts can name them. Without a row the giving
# forms and the M-Pesa prompt resolve nothing, and the treasurer's
# desk will not credit a gift for a department that has no fund.
#
# The church keeps one flat fund per department: a member named by
# description or short name (``aym``, ``awm``, ``deaconate``) lands in
# its own account, and the department desk reads that balance and the
# movements instead of the church's self-fund.
#
# The department desk finds a fund through ``TreasuryAccount.department``
# (see views.department_account), so the department must be *set* on the
# row — filtering on ``department__code`` alone would create an unlinked
# account that no desk ever reads.
#
# Depends on 0065 which creates TreasuryAccount — the schema must have
# been migrated before this runs.

from django.db import migrations, transaction


def seed_treasury_accounts(apps, schema_editor):
    Department = apps.get_model("members", "Department")
    TreasuryAccount = apps.get_model("members", "TreasuryAccount")

    accounts = [
        # (department code, M-Pesa name, description, account type)
        ("aym", "AYM", "Adventist Youth Ministry", "bank"),
        ("awm", "AWM", "Adventist Women's Ministries", "bank"),
        ("deaconate", "Deaconate", "Deaconate", "bank"),
    ]

    with transaction.atomic():
        for dept_code, name, description, account_type in accounts:
            department = Department.objects.filter(code=dept_code).first()
            if department is None:
                # The department is seeded by an earlier migration; with no
                # department there is nothing for the fund to belong to.
                continue
            # One fund per department, keyed on the department itself so a
            # re-run adopts the existing fund rather than opening a second.
            TreasuryAccount.objects.get_or_create(
                department=department,
                defaults={
                    "name": name,
                    "account_number": "",
                    "account_type": account_type,
                    "balance": 0.00,
                    "description": description,
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0172_cashcontribution_payment_group"),
        ("members", "0065_treasuryaccount_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_treasury_accounts, migrations.RunPython.noop),
    ]
