# Generated by Codebuff 🤖 — do not edit by hand.
#
# Repairs the department funds migration 0173 left half-done.
#
# 0173 looked up an account with ``department__code=...``, which only
# *filters* — it never assigned the department. So on a church that
# already had a fund (the treasurer had opened AYM and AWM and money was
# flowing in), the migration found no linked row, created a second, empty
# account beside the real one, and linked neither. The department desk
# reads ``TreasuryAccount.department`` (views.department_account), so the
# desk still reported "no account yet" and the real fund stayed invisible.
#
# This migration attaches the fund the church has actually been giving
# into — the row holding a balance or movements — to its department, and
# deletes the untouched duplicates 0173 created so the giving form does
# not offer the same fund twice. Idempotent: a second run finds nothing
# to change.

from django.db import migrations, transaction


# (department code, the account's M-Pesa name)
FUNDS = [
    ("aym", "AYM"),
    ("awm", "AWM"),
    ("deaconate", "Deaconate"),
]


def link_department_accounts(apps, schema_editor):
    Department = apps.get_model("members", "Department")
    TreasuryAccount = apps.get_model("members", "TreasuryAccount")
    WithdrawalRequest = apps.get_model("members", "DepartmentWithdrawalRequest")

    with transaction.atomic():
        for dept_code, name in FUNDS:
            department = Department.objects.filter(code=dept_code).first()
            if department is None:
                continue

            # One fund per department, so if one is already linked it is the
            # fund; the desk reads it by id and a second would sit unseen.
            account = (
                TreasuryAccount.objects.filter(department=department)
                .order_by("id")
                .first()
            )
            candidates = list(
                TreasuryAccount.objects.filter(name__iexact=name).order_by("id")
            )

            if account is None:
                if not candidates:
                    continue
                # The church's fund is the one that holds money or has
                # movements; an untouched row is the seed's leftover.
                account = next(
                    (a for a in candidates if a.balance or a.transactions.exists()),
                    candidates[0],
                )
                account.department = department
                if not (account.description or "").strip():
                    account.description = name
                account.save(update_fields=["department", "description"])

            # Remove the empty duplicates beside the fund. Only untouched,
            # unlinked rows are deleted — anything holding money, movements,
            # or a withdrawal request is left alone.
            for other in candidates:
                if other.id == account.id or other.department_id is not None:
                    continue
                if other.balance or other.transactions.exists():
                    continue
                if WithdrawalRequest.objects.filter(account=other).exists():
                    continue
                other.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0173_seed_treasury_accounts"),
    ]

    operations = [
        migrations.RunPython(link_department_accounts, migrations.RunPython.noop),
    ]
