# Generated by Codebuff 🤖 — do not edit by hand.
#
# Connects the rest of the church's desks to their funds.
#
# 0173 seeded AYM, AWM and Deaconate funds and 0174 repaired their links,
# but the other desks still read "no account yet" on the accounts page:
# the church holds their money in accounts the treasurer named by hand
# (the choir's Ensemble fund, Health, Sabbath School), and no row ever
# pointed those accounts at their desks. A desk finds its fund only
# through ``TreasuryAccount.department`` (views.department_account), so
# an unlinked account — however much it holds — is invisible to the desk
# and its leadership cannot request a withdrawal of it.
#
# This migration links those funds, moving Deaconate onto LCB as the
# church directs, and sweeps up any other desk whose fund is an
# exact-name match (an "AMM" account beside the AMM desk, and so on).
# Idempotent: linked desks are left alone on a second run.

from django.db import migrations, transaction


# The account name field is the M-Pesa reference Safaricom shows in the
# prompt, capped at 12 characters — so a created row carries a short name
# and the desk's full wording rides the description.
MAX_NAME = 12

# (department code, the account's M-Pesa name, its description when creating)
FUNDS = [
    ("choir", "Ensemble", "Choir / Ensemble"),
    ("health", "Health", "Health Ministries"),
    ("sabbath_school", "Sabbath School", "Sabbath School"),
    ("deaconate", "LCB", "Local Church Budget"),
]


def find_account(TreasuryAccount, name, description):
    """The church's fund for a desk, matched the way the church named it.

    Exact name first, then a prefix (Safaricom's 12-character cap means
    'Sabbath School' may sit on disk as 'Sabbath Sch'), then by description —
    so the treasurer's own wording, not this migration's, wins when they
    differ.
    """
    for queryset in (
        TreasuryAccount.objects.filter(name__iexact=name),
        TreasuryAccount.objects.filter(name__istartswith=name[:MAX_NAME]),
        TreasuryAccount.objects.filter(description__icontains=description),
    ):
        found = queryset.order_by("id").first()
        if found is not None:
            return found
    return None


def link_department_funds(apps, schema_editor):
    Department = apps.get_model("members", "Department")
    TreasuryAccount = apps.get_model("members", "TreasuryAccount")

    with transaction.atomic():
        for dept_code, name, description in FUNDS:
            department = Department.objects.filter(code=dept_code, is_active=True).first()
            if department is None:
                continue

            # One fund per department: the desk reads the first account
            # pointed at it, so the old link is detached before the new one
            # is set — Deaconate moves to LCB by the church's direction.
            # Detached rows are never deleted; money or movements on them
            # are the treasurer's to move at the accounts desk.
            for previous in TreasuryAccount.objects.filter(department=department):
                previous.department = None
                previous.save(update_fields=["department"])

            account = find_account(TreasuryAccount, name, description)
            if account is None:
                account = TreasuryAccount.objects.create(
                    name=name[:MAX_NAME],
                    description=description,
                    account_type="bank",
                )
            elif account.department_id not in (None, department.id):
                # The fund is already another desk's money — never steal it.
                # The desk keeps reading "no account yet" until the treasurer
                # opens one for it.
                continue
            account.department = department
            if not (account.description or "").strip():
                account.description = description
            account.save(update_fields=["department", "description"])

        # The rest of the desks: any active department still without a fund
        # takes an unlinked account that carries its exact name — the church
        # names a fund after its desk, so "AMM" beside the AMM desk links
        # itself. Exact names only; a near miss stays unlinked rather than
        # attaching the wrong money to a desk.
        for department in Department.objects.filter(is_active=True):
            if TreasuryAccount.objects.filter(department=department).exists():
                continue
            spare = (
                TreasuryAccount.objects.filter(
                    name__iexact=department.name, department__isnull=True
                )
                .order_by("id")
                .first()
            )
            if spare is not None:
                spare.department = department
                if not (spare.description or "").strip():
                    spare.description = department.name
                spare.save(update_fields=["department", "description"])


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0174_link_department_treasury_accounts"),
    ]

    operations = [
        migrations.RunPython(link_department_funds, migrations.RunPython.noop),
    ]
