# Generated by Codebuff 🤖 — do not edit by hand.
#
# Pathfinders joins the children's bands as a department of its own.
#
# 0167 made the bands (Beginners, Kindergarten, Primary, Junior, Teens)
# departments of their own, but Pathfinders — the club for juniors and teens
# — was left behind as a sub-unit of Children's Ministry. The church runs it
# as an area with its own leadership, roll and calendar, and the backend has
# always named it: the "Pathfinders Leader" role maps to the pathfinders_leader
# flag. So it gets a desk of its own, filed under the Department heading
# beside the other bands, and 0177 takes it off Children's sub-units.
#
# Same roles as its sibling bands (0167: a Leader who takes an assistant).
# Idempotent: an existing Pathfinders row is adopted, never duplicated.

from django.db import migrations
from django.utils import timezone


PATHFINDERS_ROLES = (
    ("Leader", True),
    ("Assistant", True),
)


def seed_pathfinders(apps, schema_editor):
    Department = apps.get_model("members", "Department")
    DepartmentRole = apps.get_model("members", "DepartmentRole")

    pathfinders, _created = Department.objects.get_or_create(
        code="pathfinders",
        defaults={
            "name": "Pathfinders",
            "group": "department",
            "sort_order": 25,
            "description": (
                "The Pathfinder Club: juniors and teens growing in faith, "
                "service and the outdoors."
            ),
            "created_at": timezone.now(),
        },
    )
    for index, (role_name, assistant) in enumerate(PATHFINDERS_ROLES):
        DepartmentRole.objects.get_or_create(
            department=pathfinders, name=role_name,
            defaults={"has_assistant": assistant, "sort_order": index},
        )


def unseed(apps, schema_editor):
    Department = apps.get_model("members", "Department")
    Department.objects.filter(code="pathfinders").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0175_link_remaining_department_funds"),
    ]

    operations = [
        migrations.RunPython(seed_pathfinders, unseed),
    ]
