# Generated by Codebuff 🤖 — do not edit by hand.
#
# Children's Ministry keeps its bands as departments, not as sub-units.
#
# 0167 made the children's bands (Beginners, Kindergarten, Primary, Junior,
# Teens) departments of their own and took them off Children's ``units``.
# 0168 then wrote the band list back into ``units``, so every band showed
# twice — once as a department and once as a Children's sub-unit — and
# Pathfinders, which then had no desk of its own, stayed there. 0176 has now
# given Pathfinders its own department too, so no band belongs to Children's
# units any more.
#
# This migration drops every Children unit whose wording names a department of
# its own; a unit with no department behind it — the church's own addition —
# stays. Idempotent: a second run finds nothing to change.

from django.db import migrations


def drop_department_units(apps, schema_editor):
    Department = apps.get_model("members", "Department")
    children = Department.objects.filter(code="children").first()
    if children is None:
        return

    # Every area's name, lower-cased: a unit whose wording names an area is a
    # desk of its own and must not also read as a sub-unit.
    own_area_names = {
        name.strip().lower()
        for name in Department.objects.values_list("name", flat=True)
        if name and name.strip()
    }

    kept = [
        unit.strip()
        for unit in (children.units or "").split(",")
        if unit.strip() and unit.strip().lower() not in own_area_names
    ]
    units = ", ".join(kept)
    if units != (children.units or ""):
        children.units = units
        children.save(update_fields=["units"])


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0176_pathfinders_department"),
    ]

    operations = [
        migrations.RunPython(drop_department_units, migrations.RunPython.noop),
    ]
