# Generated by Codebuff 🤖 — do not edit by hand.
#
# The departments' names read in full — the abbreviation moves out of the name.
#
# A department's stored name is what a desk's page heading and the leadership
# directory read; the rail keeps its own short forms (AMM, AYM…) beside them.
# The stored names carried their abbreviations as a suffix — "Adventist Men
# Ministries (AMM)" — so the headings never read quite in full. This migration
# spells each of the four out; fresh installs seed these names directly (the
# SEED_DEPARTMENTS list in models.py carries them too).
#
# Idempotent: a second run writes the same names again.

from django.db import migrations

#: code → the name the church reads, in full.
FULL_DEPARTMENT_NAMES = {
    'amm': 'Adventist Men Ministry',
    'awm': 'Adventist Women Ministry',
    'aym': 'Adventist Youth Ministry',
    'apm': 'Adventist Possibility Ministries',
}

#: What each name was, for the migration's reverse.
ABBREVIATED_DEPARTMENT_NAMES = {
    'amm': 'Adventist Men Ministries (AMM)',
    'awm': 'Adventist Women Ministries (AWM)',
    'aym': 'Adventist Youth (AYM)',
    'apm': 'Adventist Possibility Ministries (APM)',
}


def rename_departments(apps, schema_editor):
    Department = apps.get_model('members', 'Department')
    for code, name in FULL_DEPARTMENT_NAMES.items():
        Department.objects.filter(code=code).update(name=name)


def restore_departments(apps, schema_editor):
    Department = apps.get_model('members', 'Department')
    for code, name in ABBREVIATED_DEPARTMENT_NAMES.items():
        Department.objects.filter(code=code).update(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0177_children_units_drop_bands'),
    ]

    operations = [
        migrations.RunPython(rename_departments, restore_departments),
    ]
