# Generated by Antigravity 🚀
#
# Connects all church departments and ministries to their treasury accounts.
#
# Ensures every department and ministry desk has a linked TreasuryAccount
# so that its leadership and members can view their fund balance, browse all
# transactions in a scrollable ledger, and raise funding/withdrawal requests.

from django.db import migrations, transaction

MAX_NAME = 12

# (department_code, primary_account_name, description, fallback_match_names)
DEPARTMENT_ACCOUNT_MAPPINGS = [
    ("amm", "AMO", "Adventist Men Ministry", ["AMO", "AMM", "Adventist Men", "Men"]),
    ("awm", "AWM", "Adventist Women Ministry", ["AWM", "Adventist Women", "Women"]),
    ("aym", "AYM", "Adventist Youth Ministry", ["AYM", "Adventist Youth", "Youth"]),
    ("children", "Children", "Children Ministry", ["Children", "Children Ministry", "Child"]),
    ("pathfinders", "Pathfinder", "Pathfinders", ["Pathfinder", "Pathfinders", "Adventurers"]),
    ("chaplaincy", "Chaplaincy", "Chaplaincy Ministry", ["Chaplaincy", "Chaplaincy Ministry"]),
    ("apm", "Possibility", "Adventist Possibility Ministries", ["Possibility", "APM", "Possibility Ministries"]),
    ("choir", "Ensemble", "Choir / Ensemble", ["Ensemble", "Choir"]),
    ("music", "Music", "Music Ministry", ["Music", "Ensemble"]),
    ("health", "Health", "Health Ministries", ["Health", "Health Ministries"]),
    ("sabbath_school", "SabbathSch", "Sabbath School", ["SabbathSch", "Sabbath School"]),
    ("personal_ministries", "Evangelism", "Personal Ministries", ["Evangelism", "Personal Ministries", "Personal Min"]),
    ("eldership", "Elders", "Elders Kitty", ["Elders", "Elders Kitty", "Eldership"]),
    ("deaconate", "LCB", "Local Church Budget", ["LCB", "Local Church Budget", "Deaconate", "Deaconry"]),
    ("ambassadors", "Ambassadors", "Ambassadors", ["Ambassadors", "Ambassador"]),
    ("young_couples", "Couples", "Young Couples Fellowship", ["Couples", "Young Couples", "Family"]),
    ("single_parents", "SingleParent", "Single Parents Fellowship", ["SingleParent", "Single Parents"]),
]


def find_or_link_account(Department, TreasuryAccount, dept_code, primary_name, description, match_names):
    dept = Department.objects.filter(code=dept_code, is_active=True).first()
    if not dept:
        return

    # If already linked, make sure description is set
    existing = TreasuryAccount.objects.filter(department=dept).order_by("id").first()
    if existing:
        if not (existing.description or "").strip():
            existing.description = description
            existing.save(update_fields=["description"])
        return

    # Look for candidate accounts by name or description
    candidate = None
    for name in match_names:
        found = (
            TreasuryAccount.objects.filter(name__iexact=name, department__isnull=True)
            .order_by("id")
            .first()
        )
        if not found:
            found = (
                TreasuryAccount.objects.filter(description__icontains=name, department__isnull=True)
                .order_by("id")
                .first()
            )
        if found:
            candidate = found
            break

    if candidate is not None:
        candidate.department = dept
        if not (candidate.description or "").strip():
            candidate.description = description
        candidate.save(update_fields=["department", "description"])
    else:
        # Create dedicated treasury account
        TreasuryAccount.objects.create(
            name=primary_name[:MAX_NAME],
            description=description,
            account_type="bank",
            department=dept,
        )


def link_all_department_accounts(apps, schema_editor):
    Department = apps.get_model("members", "Department")
    TreasuryAccount = apps.get_model("members", "TreasuryAccount")

    with transaction.atomic():
        for dept_code, primary_name, description, match_names in DEPARTMENT_ACCOUNT_MAPPINGS:
            find_or_link_account(Department, TreasuryAccount, dept_code, primary_name, description, match_names)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0178_department_names_in_full"),
    ]

    operations = [
        migrations.RunPython(link_all_department_accounts, noop_reverse),
    ]
