# Generated by Django 5.2.17 on 2026-10-06 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0179_link_all_department_ministry_accounts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentwithdrawalrequest',
            name='elder_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='departmentwithdrawalrequest',
            name='elder_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_withdrawals_elder_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='departmentwithdrawalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('elder_approved', 'Elder Approved'), ('approved', 'Approved'), ('declined', 'Declined'), ('reversed', 'Reversed')], db_index=True, default='pending', max_length=20),
        ),
    ]
