# Generated by Antigravity 🚀

from django.db import migrations, transaction

def seed_departments(apps, schema_editor):
    Department = apps.get_model('members', 'Department')
    TreasuryAccount = apps.get_model('members', 'TreasuryAccount')

    with transaction.atomic():
        # 1. Development Ministry
        dev, _ = Department.objects.get_or_create(
            code='development',
            defaults={
                'name': 'Church Development & Building',
                'sort_order': 17,
                'is_active': True,
            }
        )
        # Link to Development / Church Plot account if available
        dev_account = (
            TreasuryAccount.objects.filter(name__iexact='Dev').first() or
            TreasuryAccount.objects.filter(name__icontains='dev').first() or
            TreasuryAccount.objects.filter(description__icontains='development').first() or
            TreasuryAccount.objects.filter(description__icontains='plot').first()
        )
        if not dev_account:
            dev_account = TreasuryAccount.objects.create(
                name='Dev',
                description='Church Development & Plot',
                account_type='bank',
                department=dev,
            )
        elif not dev_account.department:
            dev_account.department = dev
            dev_account.save(update_fields=['department'])

        # 2. Dorcas Ministry
        dorcas, _ = Department.objects.get_or_create(
            code='dorcas',
            defaults={
                'name': 'Dorcas Ministry',
                'sort_order': 18,
                'is_active': True,
            }
        )
        # Link to Nyakundis / Dorcas account if available
        dorcas_account = (
            TreasuryAccount.objects.filter(name__icontains='nyakundi').first() or
            TreasuryAccount.objects.filter(description__icontains='nyakundi').first() or
            TreasuryAccount.objects.filter(description__icontains='dorcas').first()
        )
        if not dorcas_account:
            dorcas_account = TreasuryAccount.objects.create(
                name='Nyakundis',
                description='Nyakundis / Dorcas Welfare',
                account_type='bank',
                department=dorcas,
            )
        elif not dorcas_account.department:
            dorcas_account.department = dorcas
            dorcas_account.save(update_fields=['department'])


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0180_withdrawal_elder_approval_reverse'),
    ]

    operations = [
        migrations.RunPython(seed_departments, migrations.RunPython.noop),
    ]
