# Generated by Antigravity 🚀

from django.db import migrations

def set_ministry_group(apps, schema_editor):
    Department = apps.get_model('members', 'Department')
    Department.objects.filter(code__in=['development', 'dorcas', 'welfare']).update(group='ministry')

class Migration(migrations.Migration):

    dependencies = [
        ('members', '0181_seed_development_and_dorcas'),
    ]

    operations = [
        migrations.RunPython(set_ministry_group, migrations.RunPython.noop),
    ]
