# Generated by Antigravity 🚀

from django.db import migrations

def update_transaction_descriptions(apps, schema_editor):
    TreasuryAccountTransaction = apps.get_model('members', 'TreasuryAccountTransaction')
    Contribution = apps.get_model('members', 'Contribution')
    CashContribution = apps.get_model('members', 'CashContribution')
    MemberProfile = apps.get_model('members', 'MemberProfile')
    User = apps.get_model('auth', 'User')

    def get_giver_name(donor_name, member_id=None, email='', phone=''):
        name = (donor_name or '').strip()
        if name and name.lower() != 'anonymous giver':
            return name
        if member_id:
            try:
                user = User.objects.filter(id=member_id).first()
                if user:
                    full = f"{user.first_name or ''} {user.last_name or ''}".strip()
                    if full:
                        return full
                    if user.username:
                        return user.username
            except Exception:
                pass
        email = (email or '').strip()
        phone_digits = ''.join(ch for ch in (phone or '') if ch.isdigit())
        if email:
            u = User.objects.filter(email__iexact=email).first()
            if u:
                full = f"{u.first_name or ''} {u.last_name or ''}".strip()
                if full:
                    return full
        if len(phone_digits) >= 9:
            mp = MemberProfile.objects.filter(phone_number__endswith=phone_digits[-9:]).first()
            if mp and mp.user:
                full = f"{mp.user.first_name or ''} {mp.user.last_name or ''}".strip()
                if full:
                    return full
        return ''

    # Build reference lookup
    giver_by_ref = {}
    for c in Contribution.objects.exclude(status='failed').exclude(status='cancelled').iterator():
        g = get_giver_name(c.donor_name, member_id=c.member_id, email=c.donor_email, phone=c.phone_number)
        if g:
            if c.mpesa_receipt_number:
                giver_by_ref[c.mpesa_receipt_number] = g
            if c.paystack_reference:
                giver_by_ref[c.paystack_reference] = g
            giver_by_ref[f"CONTRIB-{c.id}"] = g

    for cc in CashContribution.objects.iterator():
        g = get_giver_name(cc.donor_name, email=cc.giver_email, phone=cc.giver_phone)
        if g:
            if cc.receipt_number:
                giver_by_ref[cc.receipt_number] = g
            giver_by_ref[f"CASH-{cc.id}"] = g

    for tx in TreasuryAccountTransaction.objects.filter(description__startswith='Contribution —').iterator():
        ref = (tx.reference or '').strip()
        g = giver_by_ref.get(ref)
        if g:
            new_desc = tx.description.replace('Contribution —', f'{g} —', 1)[:255]
            TreasuryAccountTransaction.objects.filter(id=tx.id).update(description=new_desc)


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0182_set_development_dorcas_ministries'),
    ]

    operations = [
        migrations.RunPython(update_transaction_descriptions, migrations.RunPython.noop),
    ]
