# Generated by Django 5.2.17 on 2026-10-07 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0183_update_treasury_transaction_descriptions_with_giver'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentevent',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='departmentevent',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='departmentevent',
            name='meeting_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='departmentevent',
            name='mode',
            field=models.CharField(choices=[('physical', 'Physical'), ('virtual', 'Virtual')], default='physical', max_length=10),
        ),
        migrations.AddField(
            model_name='departmentevent',
            name='program_file',
            field=models.FileField(blank=True, null=True, upload_to='dept_event_programs/'),
        ),
        migrations.AlterField(
            model_name='departmentevent',
            name='event_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('clerk', 'Church Clerk'), ('elder', 'Elder'), ('first_elder', 'First Elder'), ('second_elder', 'Second Elder'), ('third_elder', 'Third Elder'), ('pastor', 'Church Pastor'), ('head_deacon', 'Head Deacon'), ('head_deaconess', 'Head Deaconess'), ('treasurer', 'Treasurer'), ('pm_leader', 'PM Leader'), ('apm_leader', 'APM Leader'), ('men_ministry', 'AMM Leader'), ('women_ministry', 'AWM Leader'), ('youth_leader', 'Youth Leader'), ('chaplaincy', 'Chaplaincy Leader'), ('children_ministry', 'Children Leader'), ('health_leader', 'Health Leader'), ('ambassadors_leader', 'Ambassadors Leader'), ('education_leader', 'Education Leader'), ('family_life', 'Family Life'), ('pathfinders_leader', 'Pathfinders Leader'), ('adventurers_leader', 'Adventurers Leader'), ('publishing_head', 'Publishing Head'), ('welfare_leader', 'Welfare Leader'), ('interest_coordinator', 'Interest Coordinator'), ('development', 'Development Leader'), ('dorcas_leader', 'Dorcas Leader'), ('choir_director', 'Choir Director'), ('admin', 'Administrator')], default='member', help_text="Primary/legacy role kept in sync with 'roles'", max_length=30),
        ),
        migrations.AlterField(
            model_name='rolehistory',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('clerk', 'Church Clerk'), ('elder', 'Elder'), ('first_elder', 'First Elder'), ('second_elder', 'Second Elder'), ('third_elder', 'Third Elder'), ('pastor', 'Church Pastor'), ('head_deacon', 'Head Deacon'), ('head_deaconess', 'Head Deaconess'), ('treasurer', 'Treasurer'), ('pm_leader', 'PM Leader'), ('apm_leader', 'APM Leader'), ('men_ministry', 'AMM Leader'), ('women_ministry', 'AWM Leader'), ('youth_leader', 'Youth Leader'), ('chaplaincy', 'Chaplaincy Leader'), ('children_ministry', 'Children Leader'), ('health_leader', 'Health Leader'), ('ambassadors_leader', 'Ambassadors Leader'), ('education_leader', 'Education Leader'), ('family_life', 'Family Life'), ('pathfinders_leader', 'Pathfinders Leader'), ('adventurers_leader', 'Adventurers Leader'), ('publishing_head', 'Publishing Head'), ('welfare_leader', 'Welfare Leader'), ('interest_coordinator', 'Interest Coordinator'), ('development', 'Development Leader'), ('dorcas_leader', 'Dorcas Leader'), ('choir_director', 'Choir Director'), ('admin', 'Administrator')], max_length=30),
        ),
    ]
