# Generated by Django 5.2.17 on 2026-10-08 12:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0185_fundraisingcampaign_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraisingcampaign',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
