# Generated by Django 5.2.17 on 2026-10-09 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0186_fundraisingcampaign_start_date_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentjoinrequest',
            name='kind',
            field=models.CharField(choices=[('join', 'Join the ministry or department'), ('singing_group', 'Register a singing group')], default='join', max_length=20),
        ),
    ]
