# Generated by Django 5.2.17 on 2026-10-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0187_rename_join_kind_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='needs_review',
            field=models.BooleanField(default=False, help_text="A paybill payment whose reference matched no account; awaiting a treasurer's assignment."),
        ),
    ]
