"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";

const API_URL = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000";

export default function EnrollPage() {
  const [form, setForm] = useState({ email: "", first_name: "", last_name: "", phone_number: "" }); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setMessage(""); try { const response = await fetch(`${API_URL}/api/members/auth/enrollment-request/`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const data = await response.json(); if (!response.ok) throw new Error(Object.values(data).flat().join(" ")); setMessage(data.message); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to submit your request."); } finally { setLoading(false); } }
  return <main className="flex min-h-screen items-start justify-center bg-[#f7f4ee] px-6 pt-16 text-[#26352f]"><section className="w-full max-w-md rounded-3xl bg-white p-8 shadow-sm ring-1 ring-[#dfdbd1] sm:p-10"><h1 className="text-3xl font-semibold">Request member enrollment</h1><p className="mt-3 text-sm leading-6 text-[#617068]">Use the email address where you want to receive your account setup link.</p><form onSubmit={submit} className="mt-8 space-y-5"><label className="block text-sm font-medium">Email<input type="email" required value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} className="mt-2 w-full rounded-xl border border-[#c9c5bb] px-4 py-3" /></label><div className="grid gap-5 sm:grid-cols-2"><label className="block text-sm font-medium">First name<input value={form.first_name} onChange={(event) => setForm({ ...form, first_name: event.target.value })} className="mt-2 w-full rounded-xl border border-[#c9c5bb] px-4 py-3" /></label><label className="block text-sm font-medium">Last name<input value={form.last_name} onChange={(event) => setForm({ ...form, last_name: event.target.value })} className="mt-2 w-full rounded-xl border border-[#c9c5bb] px-4 py-3" /></label></div><label className="block text-sm font-medium">Phone number<input required placeholder="e.g. 01XX XXX XXX or 07XX XXX XXX" value={form.phone_number} onChange={(event) => setForm({ ...form, phone_number: event.target.value })} className="mt-2 w-full rounded-xl border border-[#c9c5bb] px-4 py-3" /></label><button disabled={loading} className="w-full rounded-full bg-[#26352f] px-5 py-3.5 font-medium text-white disabled:opacity-60">{loading ? "Sending..." : "Request enrollment link"}</button></form>{message && <p className="mt-5 rounded-xl bg-[#f7f4ee] p-4 text-sm text-[#617068]">{message}</p>}<Link href="/login" className="mt-6 block text-center text-sm font-semibold text-[#b36b3c]">Back to sign in</Link></section></main>;
}
