"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

const API_URL = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000";
const defaultAnnouncements = [{ title: "Sabbath worship", text: "Join us every Saturday for worship, fellowship, and a place to belong.", detail: "Our weekly Sabbath gathering is a time for Bible study, worship, prayer, and fellowship across generations.", href: "/calendar?month=all&search=Sabbath", visibility: "public" }, { title: "Midweek Vespers", text: "Pause in the middle of the week for prayer and encouragement online.", detail: "Make space for prayer and spiritual encouragement with the church family during the week.", href: "/calendar?month=all&search=Midweek%20Vespers", visibility: "public" }, { title: "Serve with us", text: "Explore ministries, outreach, and practical ways to care for our community.", detail: "There is a place for every gift. Discover ways to serve through ministries, Evangelism, and Church welfare.", href: "/ministries", visibility: "public" }];
type Announcement = { id?: number; title: string; text: string; detail: string; href: string; visibility: string; expires_at?: string | null };

export default function AnnouncementsPage() {
  const [announcements, setAnnouncements] = useState<Announcement[]>(defaultAnnouncements);
  useEffect(() => { const token = localStorage.getItem("access_token"); fetch(`${API_URL}/api/members/announcements/`, { headers: token ? { Authorization: `Bearer ${token}` } : {} }).then((response) => response.ok ? response.json() : []).then((data: Announcement[]) => { if (data.length) setAnnouncements(data); }).catch(() => undefined); }, []);
  return <main className="min-h-screen bg-[#f7f4ee] px-6 py-12 text-[#26352f] sm:py-16"><div className="mx-auto max-w-5xl"><div className="max-w-3xl"><h1 className="text-4xl font-semibold tracking-tight sm:text-6xl">Announcements</h1><p className="mt-5 text-lg leading-8 text-[#617068]">Stay connected with what is happening in the Loma Linda church family.</p></div><div className="mt-12 grid gap-6">{announcements.map((announcement) => <article key={announcement.id ?? announcement.title} className="rounded-2xl border border-[#dfdbd1] bg-white p-7 sm:p-9"><div className="flex flex-wrap items-center gap-3"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-[#b36b3c]">Announcement</p>{announcement.visibility === "members" && <span className="rounded-full bg-[#eef2ed] px-3 py-1 text-xs font-semibold text-[#3d5148]">Members only</span>}{announcement.expires_at && <span className="rounded-full bg-[#f7f4ee] px-3 py-1 text-xs font-semibold text-[#617068]">Until {new Date(`${announcement.expires_at}T00:00:00`).toLocaleDateString("en-KE", { month: "short", day: "numeric" })}</span>}</div><h2 className="mt-3 text-2xl font-semibold">{announcement.title}</h2><p className="mt-4 text-base leading-7 text-[#26352f]">{announcement.text}</p>{announcement.detail && <p className="mt-3 max-w-2xl text-sm leading-6 text-[#617068]">{announcement.detail}</p>}{announcement.href && <Link href={announcement.href} className="mt-5 inline-block text-sm font-semibold text-[#b36b3c] hover:underline">Learn more &rarr;</Link>}</article>)}</div></div></main>;
}
