from django.urls import path
from .views import AdultLessonPdfRedirectView, AdultLessonRedirectView, ChildrenLessonRedirectView, MissionReadingRedirectView

from .views import AnnouncementView, BoardMeetingView, ChildDedicationRequestView, ChurchBudgetsView, ChurchCorrespondenceView, ChurchFinancialReportsView, ChurchNotificationView, ChurchSettingsView, EnrollmentCompleteView, EnrollmentDetailsView, EnrollmentOAuthVerifyView, EnrollmentRequestView, EnrollmentVerifyView, FundraisingCampaignDetailView, FundraisingCampaignListCreateView, GivingPurposeDetailView, GivingPurposeListCreateView, InitiateContributionView, MeView, MembershipTransferRequestView, MpesaCallbackView, MyContributionsView, PaystackWebhookView, PasswordResetConfirmView, PasswordResetRequestView, PrayerRequestView, RegisterView, SabbathEventsView, SupportSubmissionView, TestimonyVerificationStartView, TestimonyVerificationView, TestimonyView, VisitationRequestView

urlpatterns = [
    path('lesson-reading/adult/', AdultLessonRedirectView.as_view(), name='adult-lesson-redirect'),
    path('lesson-pdf/adult/<str:kind>/', AdultLessonPdfRedirectView.as_view(), name='adult-lesson-pdf-redirect'),
    path('lesson-reading/children/<str:division>/<str:audience>/', ChildrenLessonRedirectView.as_view(), name='children-lesson-redirect'),
    path('mission-reading/<str:audience>/', MissionReadingRedirectView.as_view(), name='mission-reading-redirect'),
    path('register/', RegisterView.as_view(), name='member-register'),
    path('me/', MeView.as_view(), name='member-me'),
    path('me/enrollment-details/', EnrollmentDetailsView.as_view(), name='member-enrollment-details'),
    path('contributions/', MyContributionsView.as_view(), name='member-contributions'),
    path('support-submissions/', SupportSubmissionView.as_view(), name='support-submissions'),
    path('contributions/initiate/', InitiateContributionView.as_view(), name='contribution-initiate'),
    path('payments/mpesa/callback/', MpesaCallbackView.as_view(), name='mpesa-callback'),
    path('payments/paystack/webhook/', PaystackWebhookView.as_view(), name='paystack-webhook'),
    path('prayer-requests/', PrayerRequestView.as_view(), name='prayer-request'),
    path('child-dedications/', ChildDedicationRequestView.as_view(), name='child-dedication'),
    path('visitations/', VisitationRequestView.as_view(), name='visitations'),
    path('testimonies/', TestimonyView.as_view(), name='testimonies'),
    path('testimonies/verify/start/', TestimonyVerificationStartView.as_view(), name='testimony-verification-start'),
    path('testimonies/verify/', TestimonyVerificationView.as_view(), name='testimony-verification'),
    path('transfers/', MembershipTransferRequestView.as_view(), name='transfers'),
    path('correspondence/', ChurchCorrespondenceView.as_view(), name='correspondence'),
    path('board-meetings/', BoardMeetingView.as_view(), name='board-meetings'),
    path('notifications/', ChurchNotificationView.as_view(), name='notifications'),
    path('reports/', ChurchFinancialReportsView.as_view(), name='church-reports'),
    path('budgets/', ChurchBudgetsView.as_view(), name='church-budgets'),
    path('sabbath-events/', SabbathEventsView.as_view(), name='sabbath-events'),
    path('church-settings/', ChurchSettingsView.as_view(), name='church-settings'),
    path('giving-purposes/', GivingPurposeListCreateView.as_view(), name='giving-purpose-list-create'),
    path('giving-purposes/<int:pk>/', GivingPurposeDetailView.as_view(), name='giving-purpose-detail'),
    path('campaigns/', FundraisingCampaignListCreateView.as_view(), name='campaign-list-create'),
    path('campaigns/<int:pk>/', FundraisingCampaignDetailView.as_view(), name='campaign-detail'),
    path('auth/enrollment-request/', EnrollmentRequestView.as_view(), name='enrollment-request'),
    path('auth/enrollment/oauth-verify/', EnrollmentOAuthVerifyView.as_view(), name='enrollment-oauth-verify'),
    path('auth/enrollment/verify/', EnrollmentVerifyView.as_view(), name='enrollment-verify'),
    path('auth/enrollment/complete/', EnrollmentCompleteView.as_view(), name='enrollment-complete'),
    path('auth/password-reset/', PasswordResetRequestView.as_view(), name='password-reset-request'),
    path('auth/password-reset/confirm/', PasswordResetConfirmView.as_view(), name='password-reset-confirm'),
    path('announcements/', AnnouncementView.as_view(), name='announcements'),
]
